### ISSUE TITLE
Scalability: Increase resync period or make parameterizable

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-provisioner#100]
The default resync period of 15 seconds is IMO too frequent.  Once there are many PVs in the system, and multiple CSI plugins, there will be a lot of unnecessary churn.  API watch is supposed to be better now and shouldn't drop events that frequently.

**Comment by msau42** [comment]
I guess the problem is the external-provisioner uses resync as its retry mechanism.  So fixing this probably requires substantial changes to external-provisioner.

**Comment by wongma7** [comment]
@msau42 Any ideas what the standard is? How high can we go? 12 hrs? It's 15 seconds for no other reasons than: copy the PV controller (which is so low only because it needs it to do its "transactions" in a timely manner) and I guess paranoia over imaginary scenarios wherein missing events leads to data deletion (???)

**Comment by wongma7** [comment]
Anyway I can definitely try to decouple resync from retries, cleaning up the retry logic may solve https://github.com/kubernetes-csi/external-provisioner/issues/101 at the same time

**Comment by msau42** [comment]
I'm not sure if there's a standard.  Searching [here](https://github.com/kubernetes/kubernetes/search?p=1&q=MinResyncPeriod&unscoped_q=MinResyncPeriod), I see kubelet uses 15 minutes, component config default seems to be 12 hours.  I think once we decouple resync from retries, then we could at least increase it to something on the order of minutes.

**Comment by wongma7** [comment]
Thanks, I've opened a PR here if you/anyone is interested https://github.com/kubernetes-incubator/external-storage/pull/825 . Did some basic testing and 15 minutes seems fine. Retries are now handled by the `ratelimiting` workqueue , i.e. we AddRateLimited if Provision returns err, Forget if succeed, & never retry if retry threshold is crossed

**Comment by msau42** [comment]
/close

Will reconsider after we have better scale testing in place
