### ISSUE TITLE
Add Block volume support for CSI provisioner

### ISSUE THREAD

**Issue by mkimuram** [kubernetes-csi/external-provisioner#110]
CSI provisioner should provision Block volumes properly.

In CSI provisioner, below three logics will need to be implemented, to add Block volume support to CSI provisioner:
1. Add ```SupportsBlock``` that properly returns whether Storage Provider's plugin supports block (this will be checked by using ```ValidateVolumeCapabilities```),
2. Pass ```BlockVolume``` instead of ```MountVolume``` to ```CreateVolume``` if ```volumeMode``` is set to be ```Block``` on ```Provision```,
3. Set ```volumeMode``` to PV returned by ```Provision```.

In Storage Provider's plugin, below two logics should be implemented:
1. Return ```true``` to ```ValidateVolumeCapabilities``` with ```BlockVolume``` specified if it supports block, and return ```false``` if it doesn't,
2. Properly handle ```CreateVolume``` with ```BlockVolume``` specified, if ```ValidateVolumeCapabilities``` with ```BlockVolume``` returns ```true```.
    (In most case, no special handling would be needed, as far as I see existing provisioner/attacher codes.)

**Comment by mkimuram** [comment]
@wongma7

Now https://github.com/kubernetes-incubator/external-storage/pull/830 is merged, we are ready to implement BlockProvisioner interface for CSi provisioner. I will implement prototype of codes with above logic and will ask you for review.

**Comment by mkimuram** [comment]
@wongma7

I've implemented a [prototype](https://github.com/mkimuram/external-provisioner/commit/0847c9fca716a97117d27313e4a8fcaa5ae757bd) and confirmed that it works well with CSI RBD driver. PTAL
I will write unit tests and make a PR, if implementation policy looks good to you.

In addition, as a result of my investigation on the current CSI driver implementations, all the drivers below use blacklisting for ```ValidateVolumeCapabilities``` and they don't check ```AccessType``` and just checks ```AccessMode```, currently. (Portworx checks whether ```Mount``` or ```Block``` is specified, though.)
Therefore, this kind of CSI drivers which really support ```Block``` should work without modification for CSI driver's side, because their ```ValidateVolumeCapabilities``` will return true for ```Block```. On the other hand, CSI drivers which don't support ```Block```, like Cpeh, will need to add logic to return false when ```AccessType``` is ```Block```.

- [CSI drivers](https://kubernetes-csi.github.io/docs/Drivers.html) 

Driver| Block Support | ValidateVolumeCapabilities for block | Need modification
-|-|-|-
[DigitalOcean Block Storage](https://github.com/digitalocean/csi-digitalocean/blob/master/driver/controller.go#L258)| Yes? | Return true| No
[GCE](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/gce-pd-csi-driver/controller.go#L381) | Yes | Return true | No
[Portworx](https://github.com/libopenstorage/openstorage/blob/master/csi/controller.go#L100) | Yes? | Return true | No
[RBD](https://github.com/ceph/ceph-csi/blob/master/pkg/rbd/controllerserver.go#L149) | Yes | Return true | No
[Ceph](https://github.com/ceph/ceph-csi/blob/master/pkg/cephfs/controllerserver.go#L185) | No | Return true | Yes
[ScaleIO](https://github.com/thecodeteam/csi-scaleio/blob/master/service/controller.go#L438) | Yes? | Return true | No
[vSphere](https://github.com/thecodeteam/csi-vsphere/blob/master/service/controller.go#L114) | Yes? | Return true | No

For Cinder, OpenSDS and NetApp, I guess that they need to return proper value for ```ValidateVolumeCapabilities``` to their background storage, because they will handle multiple backend storages. 

With above situation in mind, we might need to consider when to merge this feature, (a) Merge this feature after all public CSI drivers are confirmed to handle block properly, or (b) Merge this feature first and wait for all CSI drivers handle it properly after that. I think that (b) is O.K. as long as Block feature is default to false. But once it become default to true (and we plan to make it beta in this release), all drivers should be able to handle it, properly.

**Comment by mkimuram** [comment]
Also added [unit test cases](https://github.com/mkimuram/external-provisioner/commit/b754326474bc63d85a2466f936331c90d6b833b3).  Please review them.

**Comment by mkimuram** [comment]
> On the other hand, CSI drivers which don't support Block, like Cpeh, will need to add logic to return false when AccessType is Block.

Above is fixed in [issue](https://github.com/ceph/ceph-csi/issues/44). 

> For Cinder, OpenSDS and NetApp, I guess that they need to return proper value for ValidateVolumeCapabilities to their background storage, because they will handle multiple backend storages.

For multiple backend storages, I will investigate more. 
Could you give us any advices for it from OpenSDS viewpoint? @xing-yang

**Comment by wongma7** [comment]
I added one small comment to your proposed changes.

(b) sounds okay to me too but I am totally ignorant about how we expect CSI plugins to be maintained in relation to kube/other COs releases

**Comment by mkimuram** [comment]
@wongma7 

> I added one small comment to your proposed changes.

Thank you for your review and comment.
I've fixed ```Provision``` not to set ```fsType``` if it is Block PV and made PR. PTAL

Also, I updated under vendor directory to include kubernetes-incubator/external-storage#830 , instead of manually modifying it.
@rootfs Thank you for your advice in doing it. I would appreciate it if you could also check the results.

**Comment by mkimuram** [comment]
@wongma7

I made below PR to add CSI rbd/Cephfs e2e test:
   https://github.com/kubernetes/kubernetes/pull/67088
Also, I made below PR to make volume mode e2e test executed in a general way:
    https://github.com/kubernetes/kubernetes/pull/66577

Once both of them are merged, we are ready to add block volume e2e test for CSI drivers to test this feature in e2e.

**Comment by xing-yang** [comment]
@mkimuram Sorry for the late response.  I just noticed your question about OpenSDS.  Currently OpenSDS only has block API support.  This means OpenSDS CSI driver should be able to support block volume mode for all the backends it supports, but we have not got chance to validate the block volume mode support yet.  I believe Cinder is in the same situation because it only supports block APIs.

When we add File API support in OpenSDS, things will change and backends supported through File API should be only supporting filesystem volume mode.

**Comment by msau42** [comment]
cc @lpabon @saad-ali @vladimirvivien 

I think this issue covers the block issues Luis was talking about this morning
