### ISSUE TITLE
correctly indicate external-provisioner go.mod version by major for proper module resolution

### ISSUE THREAD

**Issue by jakobmoellerdev** [kubernetes-csi/external-provisioner#1110]
**What happened**:

I tried importing the command of external-provisioner with `go get github.com/kubernetes-csi/external-provisioner@v3.6.2` but couldn't because the go.mod does not properly include the version path suffix at https://github.com/kubernetes-csi/external-provisioner/blob/master/go.mod#L1

**What you expected to happen**:

I expect the version suffix to follow the major version (currently `/v3`), just like for external-snapshotter: https://github.com/kubernetes-csi/external-snapshotter/blob/master/go.mod#L1

**How to reproduce it**:

Attempt to build a go module and depend on any package of external-provisioner with `go get github.com/kubernetes-csi/external-provisioner@v3.6.2`

**Anything else we need to know?**:

Even though there aren't a lot of use cases, this is common go hygiene and shouldn't be too hard to fix.

**Environment**:
- Driver version: 3.6.2

**Comment by wenwutang1** [comment]
**hello**

**Comment by msau42** [comment]
This should be addressed for v5 at least.

/close
