### ISSUE TITLE
external-provisioner does not respect accessMode

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/external-provisioner#117]
external-provisioner hard codes access mode to:

```GO
	accessMode = &csi.VolumeCapability_AccessMode{
		Mode: csi.VolumeCapability_AccessMode_SINGLE_NODE_WRITER,
	}
```

It does not use the access mode specified on PV/PVC which means that the driver can not properly validate the `accessMode`.

Reported by @cduchesne!

**Comment by saad-ali** [comment]
In addition to passing the correct access mode to the CSI driver, after a volume is provisioned, external-provisioner should not just blindly set the access mode of the PV to the same access mode as the PVC.

Kubernetes allows a PVC to be fulfilled by a volume with looser access requirements. e.g. a PVC requesting RWO may be fulfilled by PV that is RWX. So PV access mode should be whatever the storage system specifies (not what the PVC says).

**Comment by lpabon** [comment]
I'll take care of fixing this.

**Comment by msau42** [comment]
CSI CreateVolumeResponse does not have access mode.  The assumption is that the volume provisioned must be able to support ALL the capabilities that were passed in the request.
```
 // The capabilities that the provisioned volume MUST have. SP MUST
  // provision a volume that will satisfy ALL of the capabilities
  // specified in this list. Otherwise SP MUST return the appropriate
  // gRPC error code.
```

So I think #133 is all we need for the fix.

/close
