### ISSUE TITLE
CreateVolume fails if returned capacity is 0

### ISSUE THREAD

**Issue by mariash** [kubernetes-csi/external-provisioner#127]
According to CSI spec `CreateVolume` should be able to return capacity of 0, which means it is unknown. See https://github.com/container-storage-interface/spec/blob/master/lib/go/csi/v0/csi.pb.go#L1266-L1269

But external-provisioner is failing to provision when checking the capacity since it is less than requested capacity https://github.com/kubernetes-csi/external-provisioner/blob/d946213178b9a5107f203fc047526a0c2dd2df63/pkg/controller/controller.go#L381

**Comment by adisky** [comment]
Agreed with you, I too faced the same error in cinder csi driver, we started returning capacity 
https://github.com/kubernetes/cloud-provider-openstack/pull/266/commits/c5003cdc8ed22d6acc39ec54602f2ae75eafa01e

**Comment by hoyho** [comment]
update reference of csi spec:
https://github.com/container-storage-interface/spec/blob/c3707a60a2d4a0a684ba342c048534defb74853d/csi.proto#L418

```protobuf
message Volume {
  // The capacity of the volume in bytes. This field is OPTIONAL. If not
  // set (value of 0), it indicates that the capacity of the volume is
  // unknown (e.g., NFS share).
  // The value of this field MUST NOT be negative.
  int64 capacity_bytes = 1;
```

**Comment by pohly** [comment]
@hoyho so this still is an issue, right?

/remove-lifecycle stale

**Comment by hoyho** [comment]
yes, i think we need to consider unknown size
