### ISSUE TITLE
Error：could not parse pre-release/metadata

### ISSUE THREAD

**Issue by jackhaibo** [kubernetes-csi/external-provisioner#128]
system: suse server 12 sp2 
go 1.9.2

linux-i5hz:~ # kubectl get pod
NAME                                 READY     STATUS             RESTARTS   AGE
csi-attacher-opensdsplugin-0         3/3       Running            0          1h
csi-nodeplugin-opensdsplugin-jzl76   3/3       Running            0          1h
csi-provisioner-opensdsplugin-0      2/3       CrashLoopBackOff   27         1h

linux-i5hz:~ # kubectl logs csi-provisioner-opensdsplugin-0 csi-provisioner
I0827 13:32:31.468858       1 csi-provisioner.go:70] Building kube configs for running in cluster...
panic: could not parse pre-release/metadata (-master+$Format:%h$) in version "v0.0.0-master+$Format:%h$"

goroutine 1 [running]:
github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/kubernetes/pkg/util/version.MustParseSemantic(0xc4203107e0, 0x19, 0x0)
        /home/lpabon/git/golang/csi-test/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/kubernetes/pkg/util/version/version.go:119 +0x6c
github.com/kubernetes-csi/external-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller.NewProvisionController(0x1ac85e0, 0xc4201140f0, 0x7fff314e3aa3, 0x11, 0x1aa82c0, 0xc420312900, 0xc4203107e0, 0x19, 0x0, 0x0, ...)
        /home/lpabon/git/golang/csi-test/src/github.com/kubernetes-csi/external-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:346 +0x33e
main.init.0()
        /home/lpabon/git/golang/csi-test/src/github.com/kubernetes-csi/external-provisioner/cmd/csi-provisioner/csi-provisioner.go:107 +0x6ef
main.init()
        <autogenerated>:1 +0x2f8

linux-i5hz:~ # kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"2018-08-27T09:51:29Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"2018-08-27T09:51:29Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

How is this going？

**Comment by xing-yang** [comment]
Looks like "kubectl version" doesn't format the versions properly on SUSE.  Can you open an issue on https://github.com/kubernetes/kubernetes?

**Comment by lasshpanzer** [comment]
Got that, I will open it soon.

**Comment by lasshpanzer** [comment]
@saad-ali please have a look at this issue, thanks

**Comment by xing-yang** [comment]
The code that caused the panic is in kubernetes-incubator/external-storage/lib/controller/controller.go where it calls utilversion.MustParseSemantic to check the version and decides what feature is supported. If we change that to utilversion.ParseSemantic, it can avoid throwing a panic but it still can't find the version and determine whether a feature is supported or not.

The problem here is "kubectl version" doesn't display version info on a SUSE setup while running K8S local cluster.  It could be that local cluster doesn't support SUSE.

**Comment by msau42** [comment]
From the linked bug it sounds like the problem is with the suse build.
/close
