### ISSUE TITLE
Provisioner cannot be recreated automatically if the node it's running on is down, result in cluster wide provisioning outage

### ISSUE THREAD

**Issue by yasker** [kubernetes-csi/external-provisioner#130]
Since provisioner is using the stateful set, it cannot recover automatically if the node running the provisioner is down, cause the whole cluster unable to provision new volumes.

According to https://github.com/kubernetes/kubernetes/issues/47230#issuecomment-309586908 , it's by design for the stateful set.

It was an issue with the attacher too, but now the attacher has implemented leader selection mechanism and deployed as a deployment instead of a stateful set, so it's no longer an issue for the attacher.

**Comment by jsafrane** [comment]
That's why provisioner (and attacher) should run in Deployment with leader election. IMO it's unacceptable to have a cluster without attacher or provisioner even for 5 minutes.

**Comment by yasker** [comment]
https://github.com/kubernetes-csi/external-provisioner/tree/master/deploy/kubernetes has been updated to use deployment.
