### ISSUE TITLE
Timed-out CreateVolume calls may leak volumes

### ISSUE THREAD

**Issue by gman0** [kubernetes-csi/external-provisioner#131]
Currently, external-provisioner's `CreateVolume` call has a timeout of 10s (hard-coded!) and is retried for up to 10 times:

https://github.com/kubernetes-csi/external-provisioner/blob/725706063fd1d5e567a5fff53a6dbe6e38a53d86/pkg/controller/controller.go#L427-L446

The CSI spec says ([RPC interactions CreateVolume, DeleteVolume, ListVolumes](https://github.com/container-storage-interface/spec/blob/master/spec.md#rpc-interactions)):

> It is worth noting that the plugin-generated volume_id is a REQUIRED field for the DeleteVolume RPC, as opposed to the CO-generated volume name that is REQUIRED for the CreateVolume RPC: these fields MAY NOT contain the same value. If a CreateVolume operation times out, leaving the CO without an ID with which to reference a volume, and the CO also decides that it no longer needs/wants the volume in question then the CO MAY choose one of the following paths:
>
> * Replay the CreateVolume RPC that timed out; upon success execute DeleteVolume using the known volume ID (from the response to CreateVolume).
> * Execute the ListVolumes RPC to possibly obtain a volume ID that may be used to execute a DeleteVolume RPC; upon success execute DeleteVolume.
> * The CO takes no further action regarding the timed out RPC, a volume is possibly leaked and the operator/user is expected to clean up.

Judging by the implementation, I'm guessing volumes are being leaked deliberately? If so, IMHO at least the timeout should be configurable + the [`ABORTED` error code](https://github.com/container-storage-interface/spec/blob/master/spec.md#error-scheme) should be handled properly, respecting the Plugin's ability to protect itself from leaking volumes.

If not, then this is a bug and those retried volumes (which, in the meantime, may have been created successfully) should be disposed of, although this still sounds like a waste of resources. The current policy to pick a successful `CreateVolume` response seems to be "the first `CreateVolume` to finish in 10s or less" rather than "the first finished `CreateVolume`". Such approach has also the unfortunate consequence that if no `CreateVolume` call finishes in under 10s, `Provision()` will never succeed. This can be easily reproduced with [this CSI plugin](https://github.com/gman0/slow-csi).

**Comment by pohly** [comment]
I'm seeing the same with ceph-csi, which is probably where @gman0 also saw it first.

**Comment by jsafrane** [comment]
This should be fixed by https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/29 and https://github.com/kubernetes-csi/external-provisioner/pull/216

Provisioner now tries indefinitely until CSI driver returns a volume or some final error (i.e. not timeout).
/close

**Comment by igorgonibm** [comment]
Is there a way to stop it? Our cluster continue to call CreateVolume and create volumes infinitely.

**Comment by xing-yang** [comment]
> Is there a way to stop it? Our cluster continue to call CreateVolume and create volumes infinitely.

If you delete PVC, retry to create volume will stop.

**Comment by igorgonibm** [comment]
I deleted PVC but it still happens (we use k8s v1.14)

**Comment by jsafrane** [comment]
No, it can't stop. If the driver (or gRPC underneath) returns timeout, the external-provisioner can't be sure if the error comes from gRPC or from the driver. The driver may be still provisioning the volume and succeed eventually. To make sure this volume is not leaked, the external-provisioner tries over and over until it gets a "final" error or success - something that's not timeout and the external-provisioner can be sure the provisioned volume either does not exist or it exists and then the provisioner deletes it.

**Comment by igorgonibm** [comment]
@jsafrane Somehow it stopped after about a day. Thank you
