### ISSUE TITLE
Topology spreading across provisioned StatefulSet volumes

### ISSUE THREAD

**Issue by verult** [kubernetes-csi/external-provisioner#143]
/kind feature

The intention is briefly described here: 
https://github.com/kubernetes/community/pull/2034/files#diff-8fe0dac6cc0083d59d7b6dfa91462244R170

The StatefulSet spreading logic, referred to in the design doc, is here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/util.go#L649-L665

@ddebroy

**Comment by ddebroy** [comment]
I will pick this one up. Cannot assign myself because I believe I am not a `member`.
