### ISSUE TITLE
Consider using Node & CSINodeInfo informers

### ISSUE THREAD

**Issue by verult** [kubernetes-csi/external-provisioner#144]
Currently the topology code makes individual API calls to fetch nodes and CSINodeInfo objects, and in many cases a selector is used to list a subset of objects rather than all of them. Should we use informers instead?

My take is to use an informer for CSINodeInfo objects but not Node objects. CSINodeInfo objects are only updated on CSI driver installation, which is less frequent than provision calls. Node objects are updated constantly, much more frequent than provision calls.

https://github.com/kubernetes-csi/external-provisioner/blob/393375a3af0b8fd4ea3cb9491586670c55a6eb25/pkg/controller/topology.go#L102
https://github.com/kubernetes-csi/external-provisioner/blob/393375a3af0b8fd4ea3cb9491586670c55a6eb25/pkg/controller/topology.go#L138
https://github.com/kubernetes-csi/external-provisioner/blob/393375a3af0b8fd4ea3cb9491586670c55a6eb25/pkg/controller/topology.go#L158
https://github.com/kubernetes-csi/external-provisioner/blob/393375a3af0b8fd4ea3cb9491586670c55a6eb25/pkg/controller/topology.go#L179

/cc @ddebroy

**Comment by ddebroy** [comment]
Absolutely ... we can use a SharedIndexInformer for the delayed binding scenarios where we don't need to list nodes. I will take this up (will start assigning to myself once I am added as a member - pinged Saad).

**Comment by verult** [comment]
Thanks so much Deep!

**Comment by mucahitkurt** [comment]
I'm working on this issue. cc @msau42

**Comment by msau42** [comment]
> My take is to use an informer for CSINodeInfo objects but not Node objects. CSINodeInfo objects are only updated on CSI driver installation, which is less frequent than provision calls. Node objects are updated constantly, much more frequent than provision calls.

I think Nodes are updated less frequently now that the heartbeats are in a separate object. It should be fine to have a Node informer now, and could help reduce API server load in large clusters if we don't have to List all nodes for every provision operation.
