### ISSUE TITLE
leadership election with configmaps

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/external-provisioner#157]
The external-attacher uses configmaps instead of endpoints for leadership election. The provisioner should do the same because it is more efficient (https://github.com/kubernetes/kubernetes/issues/68819#issuecomment-423098702).

**Comment by wongma7** [comment]
Leases leaderelection API will be in 1.14, let's use that.

**Comment by msau42** [comment]
Using lease now.
/close
