### ISSUE TITLE
Add rbac rules for accessing secrets

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-provisioner#164]
They should be optional as not all volume drivers will need it: https://github.com/kubernetes/kubernetes/issues/69122

**Comment by jarrpa** [comment]
This seems to be already resolved by #156. @msau42, is that right?

**Comment by msau42** [comment]
Oh, I think actually we don't want to give secret permissions by default because the ClusterRole is very broad and not all volume plugins need it.

**Comment by msau42** [comment]
I think it is ok to comment it out and add a comment with a description of when you need to enable it.

**Comment by msau42** [comment]
Fixed by #188
/close
