### ISSUE TITLE
PV is tried to be deleted even VolumeAttachment is still active.

### ISSUE THREAD

**Issue by mape90** [kubernetes-csi/external-provisioner#176]
/kind bug

**What happened**
PV deletion will not check if volume is still attached to node. This can cause situation where volume is deleted on backend while the attacher might still be checking attachment status of that volume. Then the attacher might not be able to complete if it can not scope with missing volumes. 

I hit the issue while using Cinder CSI plugin and make issue to there: https://github.com/kubernetes/cloud-provider-openstack/issues/381

It seems that at least AWS CSI has fixed this issue in their plugin side. They just return successfully when they can not find the resource while detaching or deleting volume.

**What should happen**
Do not delete PV while it has VolumeAttachment with attached state.
Or
Document that that CSI implementations should be able to scope with these kind of situations. Example volume plugin can not find volume to be detached means that it should return successfully.  

**How could it be fixed**
Check if PV has VolumeAttachment and if it has attached state.
Or
Document this behavior.

**Comment by msau42** [comment]
/lifecycle frozen

We can consider enhancing the StorageProtection feature to also prevent PV deletion while a volume is still attached. cc @jsafrane

**Comment by jim3ma** [comment]
@msau42 I can not find the StorageProtection feature in external-provisioner, how about it now?

**Comment by msau42** [comment]
This should be fixed in v2.0

**Comment by jim3ma** [comment]
Can we backport to v1.6 ?

**Comment by msau42** [comment]
Unfortunately the fix requires new rbac permissions, which we consider to
be a backwards incompatible change.
