### ISSUE TITLE
Add support for volume expansion

### ISSUE THREAD

**Issue by abrden** [kubernetes-csi/external-provisioner#187]
Hi all, I haven't seen an issue regarding this topic so I'm creating one.
CSI seems to be supporting volume expansion now [[1]](https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerexpandvolume) [[2]](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeexpandvolume)
Can the external-provisioner implement these features in order to resize volumes as seen in [here](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/)?

**Comment by msau42** [comment]
Volume expansion is provided by the external-resizer now.
/close
