### ISSUE TITLE
Migration notes

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-provisioner#190]
When migration is enabled in-tree:
1. Internal provisioner translates the StorageClass and sets the external-provisioner annotation to the CSI driver name
2. CSI external-provisioner sees the external-provisioner annotation with its name
    * If the StorageClass driver name == in-tree, then it does the translation
    * If the StorageClass driver name == CSI, then it does CSI

No feature gate on the external-provisioner is needed

In the translation part, we need to translate from in-tree Storageclass -> CSI StorageClass.  After the CreateVolume call, we need to translate Volume.Context back into in-tree VolumeSource

**Comment by msau42** [comment]
cc @davidz627 @jsafrane @msau42 @gnufied

**Comment by ddebroy** [comment]
Being worked in at https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/28

**Comment by msau42** [comment]
@ddebroy is this done?

**Comment by ddebroy** [comment]
Yes this is handled through:
1. https://github.com/kubernetes/kubernetes/pull/73653
2. https://github.com/kubernetes-csi/external-provisioner/pull/253
3. https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/34
