### ISSUE TITLE
External-provisioner fails to issue ControllerProbe request

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-csi/external-provisioner#20]
According to the [CSI spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerprobe), the CO (or its components) `shall invoke this RPC (controllerprobe) to determine readiness of the service`.  

A CSI driver that follows the language of the spec will fail if a probe RPC is not invoked prior to other operations.  If the CSI language is correct, then this constitutes a bug.

**Comment by msau42** [comment]
I believe this has been addressed by https://github.com/kubernetes-csi/external-provisioner/pull/234
/close
