### ISSUE TITLE
No credential in DeleteVolume RPC when defined StorageClass for PV is deleted already

### ISSUE THREAD

**Issue by sarjeet2013** [kubernetes-csi/external-provisioner#222]
Observed the behavior when receiving RPC call for DeleteVolume and doesn't contain the credentials passed in the Storage Class.

The issue seems to be not handling it for case where StorageClass is deleted before the RPC request for DeleteVolume is in progress:

https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L761
pkg/controller/controller.go:761
        ```if storageClass, err := p.client.StorageV1().StorageClasses().Get(storageClassName, metav1.GetOptions{}); err == nil {```

From above The error condition is not implemented when there is a storageclass defined but the storageClass is deleted before the PVC deletion in progress
In that case, the DeleteVolume request only send `VolumeId` without secrets

**Comment by msau42** [comment]
I believe https://github.com/kubernetes-csi/external-provisioner/pull/274 does this now and passes no secret on delete if it can't find it.

/close
