### ISSUE TITLE
Differentiate this repo from https://github.com/kubernetes-incubator/external-storage 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-csi/external-provisioner#223]
Given that there is https://github.com/kubernetes-incubator/external-storage/, i was wondering if we could add something to the README differentiating this repository.

Specifically, is external-storage/ really just a placeholder for the *old* way of doing things until CSI is mainstream ?  (i notice it has, for example, flex volume in it).

**Comment by msau42** [comment]
The readme for this repo has been updated. Does this help?
