### ISSUE TITLE
Missing permission: csi-provisioner cannot update resource "persistentvolumes"

### ISSUE THREAD

**Issue by darkowlzz** [kubernetes-csi/external-provisioner#231]
I was running the canary version of the provisioner with the hostpath driver and saw these in the logs:

```
I0217 14:13:45.598432       1 controller.go:1189] delete "pvc-881d9151-32bb-11e9-ba24-024270471d6d": started
I0217 14:13:45.650957       1 controller.go:1217] delete "pvc-881d9151-32bb-11e9-ba24-024270471d6d": volume deleted
I0217 14:13:45.670198       1 controller.go:1254] delete "pvc-881d9151-32bb-11e9-ba24-024270471d6d": failed to remove finalizer for persistentvolume: persistentvolumes "pvc-881d9151-32bb-11e9-ba24-024270471d6d" is forbidden: User "system:serviceaccount:default:csi-provisioner" cannot update resource "persistentvolumes" in API group "" at the cluster scope
W0217 14:13:45.670245       1 controller.go:793] Retrying syncing volume "pvc-881d9151-32bb-11e9-ba24-024270471d6d", failure 10
E0217 14:13:45.670305       1 controller.go:811] error syncing volume "pvc-881d9151-32bb-11e9-ba24-024270471d6d": persistentvolumes "pvc-881d9151-32bb-11e9-ba24-024270471d6d" is forbidden: User "system:serviceaccount:default:csi-provisioner" cannot update resource "persistentvolumes" in API group "" at the cluster scope
```

Got the rbac rules from [csi docs example page](https://kubernetes-csi.github.io/docs/example.html#create-rbac-rules-for-csi-provisioner).

Adding "update" verb to [persistentvolumes](https://github.com/kubernetes-csi/external-provisioner/blob/1cd1c20a6d4b2fcd25c98a008385b436d61d46a4/deploy/kubernetes/rbac.yaml#L29) resource rule under the ClusterRole fixed it.

```
I0217 14:16:07.266861       1 controller.go:1189] delete "pvc-7b475573-32bc-11e9-ba24-024270471d6d": started
I0217 14:16:07.320841       1 controller.go:1217] delete "pvc-7b475573-32bc-11e9-ba24-024270471d6d": volume deleted
I0217 14:16:07.331645       1 controller.go:1261] delete "pvc-7b475573-32bc-11e9-ba24-024270471d6d": persistentvolume deleted
I0217 14:16:07.331667       1 controller.go:1263] delete "pvc-7b475573-32bc-11e9-ba24-024270471d6d": succeeded
```

I can create a PR adding the rule if this should be fixed.

**Comment by pohly** [comment]
The example is out-dated. The canonical source for RBAC rules is https://github.com/kubernetes-csi/external-provisioner/tree/master/deploy/kubernetes

**Comment by pohly** [comment]
Having said that, those rules are also outdated. Can you create a PR?

**Comment by pohly** [comment]
Is this limited to the canary or does it also happen in the latest release?

**Comment by msau42** [comment]
This might have been introduced as part of https://github.com/kubernetes-csi/external-provisioner/pull/209, which was cherry-picked to release-1.0, but we haven't cut a release for yet.

**Comment by msau42** [comment]
We reversed #209, so update permissions are no longer needed
/close
