### ISSUE TITLE
One new csi secret key that apply to all the CSI operations

### ISSUE THREAD

**Issue by shay-berman** [kubernetes-csi/external-provisioner#245]
According to k8s CSI [spec](https://kubernetes-csi.github.io/docs/secrets-and-credentials.html), there are 2 ways to specify secrets for CSI plugin from the storage class:
option1 - to specify secret key per CSI operation (provisioner, controller-publish, snapshot, node-stage, node-publish...).
> csi.storage.k8s.io/provisioner-secret-name:  secret1
>   csi.storage.k8s.io/provisioner-secret-namespace: csi-plugin-namespace
>   csi.storage.k8s.io/controller-publish-secret-name: secret1
>   csi.storage.k8s.io/controller-publish-secret-namespace: csi-plugin-namespace
>   csi.storage.k8s.io/node-stage-secret-name: secret1
>   csi.storage.k8s.io/node-stage-secret-namespace: csi-plugin-namespace
>   csi.storage.k8s.io/node-publish-secret-name: secret1
>   csi.storage.k8s.io/node-publish-secret-namespace: csi-plugin-namespace
> 

option2 - to specify secret per PV name by having `${pv.name}` template.

But what if a CSI plugin requires the same credential fpr all the CSI operations?
So the user must specify many secret lines in each storage class object (5 secrets per operations + 5 namespace per operation * number of storage classes that uses the same backend).

So this issue is to propose another option(number 3) to simplify the user experience in case csi driver requires the same secret for all CSI operations. 
So the secret key in the storage class can be called:
  csi.storage.k8s.io/secret-name:  SECRET
  csi.storage.k8s.io/secret-namespace: NAMESPACE

Note: maybe we can distinguish secret for csi controller-ops vs csi node-ops, because I believe that usually the secrets for these operations are different, and maybe u don't even need secret for csi node ops at all.

**Comment by gnufied** [comment]
I think this could work. It might be considered less secure than per-sidecar secrets but if a admin wants to use same secret for all sidecards, why not.  One problem is going to be to ensure that, same key is known to all sidecars. 

cc @msau42 @liggitt
