### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by muhlba91** [kubernetes-csi/external-provisioner#258]
In https://github.com/ceph/ceph-csi/issues/284 I am running into timeout issues with the provisioner and as per discussions, a fix is to use the `timeout` cmd line argument.

However, this argument has been introduced in https://github.com/kubernetes-csi/external-provisioner/commit/45a92e290be317396c3c8f5b67a842fad85822f6#diff-38b23914da9991d96c9ec4fc3c2525aa and, therefore, is not in any stable release available yet and testing your `canary` release, the `timeout` argument solves my problem.

Hence, is there any release planned or possible now containing this argument?

**Comment by msau42** [comment]
Sorry for the delay, a new release has been tagged: https://github.com/kubernetes-csi/external-provisioner/releases/tag/v1.1.0
