### ISSUE TITLE
Update external-provisioner to set resize secrets on resizing when necessary

### ISSUE THREAD

**Issue by gnufied** [kubernetes-csi/external-provisioner#278]
Since we added https://github.com/kubernetes/kubernetes/pull/77516, we need to make sure that volume resizing secrets are set in `CSIPersistentVolumeSource` whenever they are created.

cc @leakingtapan

**Comment by ggriffiths** [comment]
@gnufied Does this issue still need to be worked on? If so, I can take look.

**Comment by gnufied** [comment]
@ggriffiths yes this issue still needs to be worked on.
