### ISSUE TITLE
Different permissions between provisioner roles in example and k8s

### ISSUE THREAD

**Issue by verult** [kubernetes-csi/external-provisioner#285]
The RBAC permissions listed in the provisioner role in the example are different from those bundled into k8s:
https://github.com/kubernetes/kubernetes/blob/4e397d971a72f5bc6dbffbacca7297f17e17c572/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L503

Should they be different? Should most users just use the built-in role?

**Comment by pohly** [comment]
See https://github.com/kubernetes-csi/external-attacher/issues/151#issuecomment-498131047
