### ISSUE TITLE
Are there any attentions or tips when I update CSI v0.3 to v1.0

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes-csi/external-provisioner#289]
Are there any attentions or tips when I update CSI v0.3 to v1.0

Recently, we plan to update our kubernetes from v1.12 to v1.14 and CSI related components from v0.3 to v1.14, is there some notice about those updates?

**Comment by msau42** [comment]
Try looking at the hostpath CSI driver as an example of a 1.14 deployment

**Comment by zhangxiaoyu-zidif** [comment]
@msau42 Many thanks~ I will try it~

**Comment by msau42** [comment]
Also see https://github.com/container-storage-interface/spec/releases/tag/v1.0.0 for full list of breaking changes.

And look at each sidecar page under https://kubernetes-csi.github.io/docs/sidecar-containers.html to see which version of the sidecar we recommend you use with which K8s release.

/close
