### ISSUE TITLE
Prefix leader election lock name with "external-provisioner-leader"

### ISSUE THREAD

**Issue by verult** [kubernetes-csi/external-provisioner#295]
CSI has many controllers with leader election functionality. It's best to disambiguate between all the different locks used for LE with a provisioner-specific prefix.

However, a rolling upgrade to a version that includes the change will result in the possibility that two different locks are used at a given time, resulting in two leaders temporarily.

Should this be reconsidered when 2.0 rolls out?

**Comment by msau42** [comment]
We should make lock namespace configurable too.

**Comment by msau42** [comment]
We can make it an option to not break backwards compatibility.

/kind feature

**Comment by verult** [comment]
For a small bug like this I don't think adding a new flag option is justified. It could potentially make the provisioner a little harder to use, and exposing anything in the user interface carries some permanence.

I'm personally OK with leaving the fix until 2.0, and make sure every other CSI controller prefixes before moving to 1.0.

**Comment by msau42** [comment]
After some discussion we decided not to do this, with the consideration that we may want to combine all the sidecars in the future.
/close
