### ISSUE TITLE
cannot create  PVC with datasource=PersistentVolumeClaim when clone PVC and source PVC storageclass name is same 

### ISSUE THREAD

**Issue by Madhu-1** [kubernetes-csi/external-provisioner#308]
logs:

`
/rbd-pvc-restore"
I0701 12:39:00.779025       1 controller.go:979] Final error received, removing PVC 1e98da4d-49d2-41b2-9c16-b9a7784caa38 from claims in progress
W0701 12:39:00.779060       1 controller.go:886] Retrying syncing claim "1e98da4d-49d2-41b2-9c16-b9a7784caa38", failure 3
E0701 12:39:00.779093       1 controller.go:908] error syncing claim "1e98da4d-49d2-41b2-9c16-b9a7784caa38": failed to provision volume with StorageClass "csi-rbd-sc": error getting handle for DataSource Type PersistentVolumeClaim by Name rbd-pvc: the source PVC and destination PVCs must be in the same storage class for cloning.  Source is in 0xc00049a470, but new PVC is in 0xc000516bb0
`

CC @j-griffith

**Comment by j-griffith** [comment]
Cloning across storage classes is intentionally unsupported, I've added a note to the csi docs to clarify a bit and make sure this is clear.  https://github.com/kubernetes-csi/docs/pull/181

**Comment by Madhu-1** [comment]
@j-griffith the issue I faced was cloning within the same storageclass

**Comment by j-griffith** [comment]
@Madhu-1 Could you provide some detail in the bug report; you have the logs here which is great, but that just says source/destination sc's differ.  There's now way I could have known that you were using the same sc there.  So it's a dereference issue it looks like?

**Comment by Madhu-1** [comment]
@j-griffith yes the issue is with storageclass name comparison

**Comment by zhucan** [comment]
@j-griffith Are we considering supporting clones that boast storage pools? or cloning across storage classes
