### ISSUE TITLE
after concurrent create 100 PVCs external-provisioner crash

### ISSUE THREAD

**Issue by GongWilliam** [kubernetes-csi/external-provisioner#322]
after concurrent create 100 PVCs external-provisioner crash.
the sidecar use leader-election (lease)

I change the work-thread number to 4, it works!
so the question is: is my cpu  too weak or the default number of work-thread too big? why set 100 to the default number of work-thread ?

**Comment by msau42** [comment]
cc @jsafrane do we really need default worker thread count to be so high?

**Comment by jsafrane** [comment]
100 was requested by @saad-ali in https://docs.google.com/document/d/1wyq_9-EFsr7U90JMYXOHxoJlChwWXJqWsah3ctmuDDo/edit?disco=AAAACevk7-4

We do not need 100, but then we need to make up another number.

@GongWilliam, what CSI driver do you use? Can you check *why* the provisioner crashed?

I created 500 PVCs with mock driver and I got them provisioned (with lot of API server throttling) in ~4 minutes without any issues. It was a VM with 4 CPU cores.

**Comment by GongWilliam** [comment]
the crash because the provisioner can not aquire the lease and then it quit, wait for the kubelet wake it up.

**Comment by zhucan** [comment]
I also encountered the same problem. after concurrent create 50 PVCs external-provisioner crash. 
Because I set the 'csi.storage.k8s.io/provisioner-secret-name' & 'csi.storage.k8s.io/provisioner-secret-namespace' in  the storageclass @jsafrane @GongWilliam

**Comment by hoyho** [comment]
Perhaps it will happen when there's too many thread have operation(read/write) on ConfigMap concurrently

**Comment by msau42** [comment]
Is there any stacktrace of the crash?

**Comment by zhucan** [comment]
logs:
 provision "default/csi-pvc48" class "expand-sc": started
I0816 11:20:29.842122       1 controller.go:596] successfully created PV {GCEPersistentDisk:nil AWSElasticBlockStore:nil HostPath:nil Glusterfs:nil NFS:nil RBD:nil ISCSI:nil Cinder:nil CephFS:nil FC:nil Flocker:nil FlexVolume:nil AzureFile:nil VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil PortworxVolume:nil ScaleIO:nil Local:nil StorageOS:nil CSI:&CSIPersistentVolumeSource{Driver:csi.block.com,VolumeHandle:csi-iscsi-pvc-85b63906-2706-4101-8e23-380d11e7d6e3,ReadOnly:false,FSType:xfs,VolumeAttributes:map[string]string{accessPaths: admin,admin1,admin2,pool: data_pool,storage.kubernetes.io/csiProvisionerIdentity: 1565925614881-8081-.csi.block.com,xmsServers: 10.255.101.225,10.255.101.226,10.255.101.227,},ControllerPublishSecretRef:nil,NodeStageSecretRef:nil,NodePublishSecretRef:nil,ControllerExpandSecretRef:nil,}}
I0816 11:20:29.842534       1 controller.go:1278] provision "default/csi-pvc42" class "expand-sc": volume "pvc-85b63906-2706-4101-8e23-380d11e7d6e3" provisioned
I0816 11:20:29.842581       1 controller.go:1295] provision "default/csi-pvc42" class "expand-sc": succeeded
I0816 11:20:29.916490       1 leaderelection.go:263] failed to renew lease default/csi-block-com: failed to tryAcquireOrRenew context deadline exceeded
F0816 11:20:29.916544       1 leader_election.go:169] stopped leading

@msau42

**Comment by msau42** [comment]
It sounds like the default 100 threads is too much for machines with fewer cores. Capturing a CPU/memory profile during stress I think would be useful to compare different values.  I think lowering the default is reasonable, but we will need to wait until we're ready for a 2.0 as changing the default is a breaking change.

For now, you can set the --worker-threads flag lower as needed.

**Comment by msau42** [comment]
/remove-lifecycle rotten
/help

Need help running some performance benchmarking to determine what a good default number would be.

**Comment by yoesmat** [comment]
The safest would probably be to set the default to some multiplier of CPU count. Without priorities on goroutines you will always risk the lease routine not getting scheduled/picked up and thus loosing the leader election.

**Comment by chrishenzie** [comment]
I attempted to repro this issue several different ways but no success.

- Using a revision prior to this change (https://github.com/kubernetes-csi/external-provisioner/pull/447)
  - Testing if API-throttling on a single k8s client could impact leader election
- Setting CPU limits (10m on the external-provisioner container)
- Sleeping during `CreateVolume()` in the mock-driver container

This was benchmarked by creating and deleting 5000 PVCs using the external-provisioner and mock-driver on a nodepool of GCE g1-smalls (1 vCPU). Creating the PVCs took ~2m, and creating all PVs took an additional ~20+ minutes, but during this time I only ever saw logs for acquiring the lease:
```
csi-provisioner I0723 23:51:01.725031       1 leaderelection.go:252] successfully acquired lease default/io-kubernetes-storage-mock
```

but never for the lease expiring. Also no pod restarts.
/close

**Comment by msau42** [comment]
Thanks for investigating! It seems like we can't repro the issue on a 1 cpu machine, and with separating out the leader election client from provisioning k8s client, that should help avoid api throttling issues, which could be one avenue of starvation.

/close

**Comment by andyzhangx** [comment]
check my large scale test result, I got a relatively accurate memory limit for `csi-provisioner`, `csi-attacher`, `csi-resizer` per below test:
 - [share large scale test result(20K volumes)](https://github.com/kubernetes-csi/external-provisioner/issues/587)
