### ISSUE TITLE
Missing Controller Expand Secret in PV

### ISSUE THREAD

**Issue by venkatsc** [kubernetes-csi/external-provisioner#332]
Hi,

For dynamically provisioned volumes, the PV is not appended with [ControllerExpandSecretRef](https://github.com/kubernetes-csi/external-provisioner/blob/5c5deb3b10799df512d7ab151f20d94b9d803218/pkg/controller/controller.go#L578). 

Kubernetes version: v1.15.1
external-provisoner: v1.3.0

**StorageClass definition**
```apiVersion: v1
items:
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    creationTimestamp: "2019-08-20T15:51:24Z"
    name: quobyte-csi
    resourceVersion: "47636"
    selfLink: /apis/storage.k8s.io/v1/storageclasses/quobyte-csi
    uid: 42150f3d-f0aa-47a3-8f14-3dce6866f2c1
  parameters:
    accessMode: "770"
    createQuota: "true"
    csi.storage.k8s.io/controller-expand-secret-name: quobyte-admin-secret
    csi.storage.k8s.io/controller-expand-secret-namespace: quobyte
    csi.storage.k8s.io/node-publish-secret-name: quobyte-admin-secret
    csi.storage.k8s.io/node-publish-secret-namespace: quobyte
    csi.storage.k8s.io/provisioner-secret-name: quobyte-admin-secret
    csi.storage.k8s.io/provisioner-secret-namespace: quobyte
    group: root
    quobyteConfig: BASE
    quobyteTenant: My Tenant
    user: root
  provisioner: csi.quobyte.com
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
**Created PV** with dynamic provisioning
```apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: csi.quobyte.com
    creationTimestamp: "2019-08-20T15:54:33Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: pvc-3fd4d1cc-040e-4450-b4a5-af4d7d7b6351
    resourceVersion: "47983"
    selfLink: /api/v1/persistentvolumes/pvc-3fd4d1cc-040e-4450-b4a5-af4d7d7b6351
    uid: 08cac5a8-cc82-4100-88ba-2b6d4f7b5079
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: quobyte-csi-test
      namespace: default
      resourceVersion: "47976"
      uid: 3fd4d1cc-040e-4450-b4a5-af4d7d7b6351
    csi:
      driver: csi.quobyte.com
      fsType: ext4
      nodePublishSecretRef:
         name: quobyte-admin-secret
         namespace: quobyte
      volumeAttributes:
         storage.kubernetes.io/csiProvisionerIdentity: 1566316251682-8081-csi.quobyte.com
      volumeHandle: 6bc9960e-f4b9-4b00-a923-73288516de81|e109cd6b-8729-48d4-abfb-74b5e26e60d8
    persistentVolumeReclaimPolicy: Retain
    storageClassName: quobyte-csi
    volumeMode: Filesystem
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
Could it possibly due to api mismatch in  [sig-storage-lib-external-provisioner](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/c525773885fccef89a1edd22bb3f813d50548ed1/controller/controller.go#L1205)?

**Comment by gnufied** [comment]
Did you had `ExpandCSIVolumes` feature gate enabled in 1.15 cluster? Because setting that field requires the feature gate to be enabled. This will change in 1.16 though

**Comment by venkatsc** [comment]
> Did you had `ExpandCSIVolumes` feature gate enabled in 1.15 cluster?

yes, this feature gate is enabled on kubelet. In fact, `ControllerExpandVolume` is called without secrets. And also, there are no checks in the provisioner on this feature gate while creating PV.

With log level 5, the below PV [creation success is logged in the provisioner](https://github.com/kubernetes-csi/external-provisioner/blob/27750ab12343e6b5d6ed1e277b161aa45bc02cfd/pkg/controller/controller.go#L596).

```I0821 10:35:42.248815       1 controller.go:596] successfully created PV {GCEPersistentDisk:nil AWSElasticBlockStore:nil HostPath:nil Glusterfs:nil NFS:nil RBD:nil ISCSI:nil Cinder:nil CephFS:nil FC:nil Flocker:nil FlexVolume:nil AzureFile:nil VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil PortworxVolume:nil ScaleIO:nil Local:nil StorageOS:nil CSI:&CSIPersistentVolumeSource{Driver:csi.quobyte.com,VolumeHandle:aa2de078-c29b-450a-819a-0a154f4f6162|66c97ce2-9569-4a01-8906-76eaa7f9de31,ReadOnly:false,FSType:ext4,VolumeAttributes:map[string]string{storage.kubernetes.io/csiProvisionerIdentity: 1566383663014-8081-csi.quobyte.com,},ControllerPublishSecretRef:nil,NodeStageSecretRef:nil,NodePublishSecretRef:&SecretReference{Name:quobyte-admin-secret,Namespace:quobyte,},ControllerExpandSecretRef:&SecretReference{Name:quobyte-admin-secret,Namespace:quobyte,},}}``` 

above log shows that the PV is appended with the configured `ControllerExpandSecret` in StorageClass -- ```ControllerExpandSecretRef:&SecretReference{Name:quobyte-admin-secret,Namespace:quobyte,}```. However, the created PV in the K8S is as below (missing the ```ControllerExpandSecretRef```). 

```apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.quobyte.com
  creationTimestamp: "2019-08-21T10:35:42Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-c03e1d55-be35-4b62-a0d2-05262a84b64d
  resourceVersion: "61916"
  selfLink: /api/v1/persistentvolumes/pvc-c03e1d55-be35-4b62-a0d2-05262a84b64d
  uid: 60ebe605-d877-4066-8398-26b6b2c8d6e0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: quobyte-csi-test
    namespace: default
    resourceVersion: "61907"
    uid: c03e1d55-be35-4b62-a0d2-05262a84b64d
  csi:
    driver: csi.quobyte.com
    fsType: ext4
    nodePublishSecretRef:
      name: quobyte-admin-secret
      namespace: quobyte
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1566383663014-8081-csi.quobyte.com
    volumeHandle: aa2de078-c29b-450a-819a-0a154f4f6162|66c97ce2-9569-4a01-8906-76eaa7f9de31
  persistentVolumeReclaimPolicy: Retain
  storageClassName: quobyte-csi
  volumeMode: Filesystem
status:
  phase: Bound
```

After the PV definition log, the external-provisioner returns and [assigns the PV object in sig-storage-lib-external-provisoner](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/c525773885fccef89a1edd22bb3f813d50548ed1/controller/controller.go#L1268). Hence, I doubt `sig-storage-lib-external-provisioner` is possibly did not pick the updated type for `CSIPersistentVolumeSource` with  [ControllerExpandSecretRef](https://github.com/kubernetes/kubernetes/blob/ef9e794a369d25f4024317dc5ca5bc04c18f887e/pkg/apis/core/types.go#L1612) and silently ignoring the the `ControllerExpandSecretRef`. Is that could be the case?

**Comment by gnufied** [comment]
Since external-provisioner is creating PV with secrets but secrets are not being applied to it, I would double check if aformentioned feature-gate is enabled on api-server.  Here is PR that added support for adding secrets during PV creation for volume expansion - https://github.com/kubernetes-csi/external-provisioner/pull/301/files

The other thing is - we do not check for feature-gates in sidecar containers. For your use case, `ExpandCSIVolumes` feature-gate must be enabled on api-server, controller-manager and kubelet. To me, this bug def. sounds like we are missing feature gate on api-server.

**Comment by venkatsc** [comment]
Thank you @gnufied. Enabling the feature gate on api-server, kube-controller, and kubelet did the work!

**Comment by HaojingLu97** [comment]
In v1.14 cluster, I encountered same issue. even if I turn on feature gates ExpandCSIVolumes on kubelet, api-server and controller manager and modified storageclass too, still missing Controller Expand Secret. And I tried manually add to PV, is showed that this field is not validated. 


I am using csi-provisioner v0.1.0.

**Comment by paullaffitte** [comment]
In v1.19 cluster I still have the same issue. How this is possible since VolumeExpansion is not in alpha anymore? I should not require any feature-gate flag right?
