### ISSUE TITLE
volume cloning failed

### ISSUE THREAD

**Issue by zhucan** [kubernetes-csi/external-provisioner#333]
k8s version: v1.15.0
external-provisioner(Previous use): v1.1.0
external-provisioner(Use now)：1.3-canary

Describe:
I had create a pvc by external-provisioner (version is v1.1.0), because of that v1.1.0 doesn't support clone so I upgrade it to 1.3-canary, When I try to create cloned volume, there are some errors :
` failed to provision volume with StorageClass "expand-sc": error getting handle for DataSource Type PersistentVolumeClaim by Name csi-pvc9: the source PVC (csi-pvc9) storageclass cannot be empty.
`

**The src pvc yaml:**
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: expand-sc
    volume.beta.kubernetes.io/storage-provisioner: csi.ebs.com
  creationTimestamp: "2019-08-16T03:20:10Z"
  finalizers:
  \- kubernetes.io/pvc-protection
  name: csi-pvc9
  namespace: default
  resourceVersion: "5941369"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/csi-pvc9
  uid: 6ed8d56f-fcd9-4abf-9357-9dd4a8d92fb5
spec:
  accessModes:
  \- ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: pvc-6ed8d56f-fcd9-4abf-9357-9dd4a8d92fb5
status:
  accessModes:
  \- ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound

**The des pvc yaml:**
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-pvc-3
    namespace: default
spec:
  storageClassName: expand-sc
  accessModes:
  \- ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: csi-pvc9

**Comment by zhucan** [comment]
@j-griffith

**Comment by zhucan** [comment]
@j-griffith I think I know the reason for the error because of that in the old yaml that I set the SC in metadata.annotations but in the clone yaml that I set the SC in spec with storageClassName. I think it is a bug

**Comment by j-griffith** [comment]
You have to have a storage class... if you do a describe on the source pvc is needs to be the same.  Going between versions of your ebs provisioner shouldn't matter, the only dependencies on the source object is the kubernetes object itself, primarily the storageClass parameter

**Comment by zhucan** [comment]
I think that it's matter to provisioner version， I have described the SC on the src pvc is same as des pvc, but creating the cloned volume failed, because of that it check the SC in the spec with storageClassname.

**Cloned volume yaml:**

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: expand-sc
    volume.beta.kubernetes.io/storage-provisioner: iscsi.csi.xsky.com
  creationTimestamp: "2019-08-22T06:12:47Z"
  finalizers:
  \- kubernetes.io/pvc-protection
  name: clone-of-pvc-3
  namespace: default
  resourceVersion: "7056190"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/clone-of-pvc-3
  uid: 3d92c9c6-c636-403b-bbee-252e78670a2d
spec:
  accessModes:
  \- ReadWriteOnce
  dataSource:
    apiGroup: null
    kind: PersistentVolumeClaim
    name: csi-pvc9
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
status:
  phase: Pending

**Comment by zhucan** [comment]
@j-griffith  @msau42  @xing-yang   I think if the "sourcePVC.Spec.StorageClassName" is nil, we can get the StorageClassName from pv as same as the external-snapshotter when cloning.

**external-provisioner:**
https://github.com/kubernetes-csi/external-provisioner/blob/0c56ab07a68cbe7b186d96f2afa8e00b5895066b/pkg/controller/controller.go#L741 
**external-snapshotter:**
https://github.com/kubernetes-csi/external-snapshotter/blob/abbefcd7fa2f4ea69503ab056e2bc0ea5a41da7d/pkg/common-controller/snapshot_controller.go#L999

**Comment by xing-yang** [comment]
@j-griffith @msau42 @jsafrane do we require sourcePVC.Spec.StorageClassName to be not nil?  What if sourcePVC is created by static-binding?

**Comment by msau42** [comment]
I think storageclass should be required so that it still counts against quota. do we also validate capacity of new PVC is >= datasource? We should make sure restore from snapshots behavior also works with quota.

**Comment by jsafrane** [comment]
Another thing is that the provisioner/cloner needs to know what kind of volume to provision. It would not be possible to distinguish in `CreateVolume` CSI call with empty parameters between "provision with no parameters" and "provision the same volume type as the original".

**Comment by j-griffith** [comment]
One of the requirements for "smart" cloning was that the source and destination must be in the same storage class.  That's the only way we can make sure that we provide an expected result (ie filesystem, iop settings, pool-type etc).  The only way to be sure of that was to compare the storage-classes between the two objects.

We did not consider the case of using the old annotation style for specifying storageClass.  It does seem like it would be possible to add a check for the old `volume.beta.kubernetes.io/storage-class:` annotation and allow that as a valid attribute in the comparison (I'm not a fan of trusting attributes for things though).  If a PVC doesn't have a storage class though it should *not* be cloneable under any circumstances, at least not through the use of the `DataSource: PVC` method.

That handles the *source* issue described here, as others point out and I've mentioned before, I wouldn't even want to entertain the idea of allowing destination volumes to be created without a storage class.  IMO that behavior should definitely remain.

I'm mixed on the idea of analyzing the attributes vs just saying "we don't allow DataSource without a StorageClassname... thoughts from everyone?

**Comment by zhucan** [comment]
@j-griffith If we create the pvc with the old volume.beta.kubernetes.io/storage-class, the pvc can be cloned. whether we have plan to check for the volume.beta.kubernetes.io/storage-class.
