### ISSUE TITLE
build make  failed with provisioner

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes-csi/external-provisioner#336]
[root@LIN-FE325E0FEA1 provisioner]# make 
mkdir -p bin
CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-X main.version=94886ea09469e1e00e2473672e122346dd871188 -extldflags "-static"' -o ./bin/csi-provisioner ./cmd/csi-provisioner
# provisioner/cmd/csi-provisioner
cmd/csi-provisioner/csi-provisioner.go:184:42: cannot use clientset (type *"provisioner/vendor/k8s.io/client-go/kubernetes".Clientset) as type "github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/kubernetes".Interface in argument to "github.com/kubernetes-csi/external-provisioner/pkg/controller".NewCSIProvisioner:
	*"provisioner/vendor/k8s.io/client-go/kubernetes".Clientset does not implement "github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/kubernetes".Interface (wrong type for AdmissionregistrationV1beta1 method)
		have AdmissionregistrationV1beta1() "provisioner/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1".AdmissionregistrationV1beta1Interface
		want AdmissionregistrationV1beta1() "github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1".AdmissionregistrationV1beta1Interface
cmd/csi-provisioner/csi-provisioner.go:184:102: cannot use snapClient (type *"provisioner/vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned".Clientset) as type "github.com/kubernetes-csi/external-provisioner/vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned".Interface in argument to "github.com/kubernetes-csi/external-provisioner/pkg/controller".NewCSIProvisioner:
	*"provisioner/vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned".Clientset does not implement "github.com/kubernetes-csi/external-provisioner/vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned".Interface (wrong type for Discovery method)
		have Discovery() "provisioner/vendor/k8s.io/client-go/discovery".DiscoveryInterface
		want Discovery() "github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/discovery".DiscoveryInterface
cmd/csi-provisioner/csi-provisioner.go:185:57: cannot use csiProvisioner (type "github.com/kubernetes-csi/external-provisioner/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller".Provisioner) as type "provisioner/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller".Provisioner in argument to "provisioner/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller".NewProvisionController:
	"github.com/kubernetes-csi/external-provisioner/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller".Provisioner does not implement "provisioner/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller".Provisioner (wrong type for Delete method)
		have Delete(*"github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/api/core/v1".PersistentVolume) error
		want Delete(*"provisioner/vendor/k8s.io/api/core/v1".PersistentVolume) error
release-tools/build.make:64: recipe for target 'build-csi-provisioner' failed
make: *** [build-csi-provisioner] Error 2

**Comment by Madhu-1** [comment]
@jianglingxia I didn't face any issue with the latest master.
