### ISSUE TITLE
Updates to docker hub to make example useful

### ISSUE THREAD

**Issue by cduchesne** [kubernetes-csi/external-provisioner#34]
Who is updating https://hub.docker.com/r/k8scsi/csi-provisioner/tags/ ? The example deployment references this docker hub repo and updates are never pushed.

**Comment by lpabon** [comment]
@cduchesne Hi, we just changed Quay.io. A new container is pushed as quay.io/k8scsi/csi-provisioner:canary on every change to the master branch.

There more info here:
https://quay.io/repository/k8scsi/csi-provisioner?tab=tags

**Comment by cduchesne** [comment]
Got it. Thanks! #38
