### ISSUE TITLE
Pass k8s API metadata through parameters in CreateVolume

### ISSUE THREAD

**Issue by davidz627** [kubernetes-csi/external-provisioner#370]
/kind feature

There is a use case for passing in k8s API metadata through parameters in CreateVolume. For example this information could be used by drivers to label underlying resources and associate them with k8s objects.

This could be done through a reserved parameter namespace e.g. `kubernetes.io/pvc.name`, `kubernetes.io/pvc.namespace`
It could be enabled by a flag so that it is not a breaking change (since some drivers may do strict validation on their own well-known parameters).

/cc @jsafrane @msau42

**Comment by davidz627** [comment]
existing tags in k8s for PD are of the form:
`kubernetes.io/created-for/pv/name`
`kubernetes.io/created-for/pvc/name`
`kubernetes.io/created-for/pvc/namespace`

**Comment by jsafrane** [comment]
There is long discussion in https://github.com/kubernetes-csi/external-provisioner/issues/86.

Technically, I would perhaps reuse expansion introduced in https://github.com/kubernetes-csi/external-provisioner/pull/69 to all parameters, so it's more obvious.  Passing PVC name + namespace + PV name would not harm. Passing PVC annotations (as introduced by the PR) is a topic for discussion, as it makes PVC not portable across clusters.

**Comment by davidz627** [comment]
I would like to avoid the sticky topic of passing in annotations and just get the parameters for PVC name, namespace, PV name for now. Wondering if anyone is working on that or if I wanted to use it in the near future if I would have to pick that up :)

**Comment by jsafrane** [comment]
> Wondering if anyone is working on that
 
Nobody that I know about. However, it *should* be a relatively simple PR, right? All the variable expansion is already done, we just need to extend it to all `storageClass.parameters`.

**Comment by davidz627** [comment]
I will pick it up
/assign

**Comment by davidz627** [comment]
didn't have time to work on this - the issue is available to pick up by anyone if interested. I will comment on this issue if I start working on it actively
/remove-lifecycle stale

**Comment by abrden** [comment]
Hi @hoyho, are you already working on this one? I happen to need this feature quite urgently and can take care of making the change if you want

**Comment by yoesmat** [comment]
How would the PV name be used? Isn't it the same as the volume name today in the CreateVolume request?

**Comment by travisghansen** [comment]
@yoesmat volume name is generally `pvc-{guid}`..It's scope would be global, where is the pvc name would be unique to namespace etc.

**Comment by yoesmat** [comment]
@travisghansen, I understand why the PVC name/namespace is useful. I am asking about PV name.

**Comment by travisghansen** [comment]
@yoesmat ok, I must have misunderstood the question. Thanks!

**Comment by yoesmat** [comment]
Thanks @travisghansen :)!

**Comment by hoyho** [comment]
> Hi @hoyho, are you already working on this one? I happen to need this feature quite urgently and can take care of making the change if you want

Yes, I do have a local branch to add this feature. Since @zetsub0u  have opened a PR , let's wait for it to merge.
