### ISSUE TITLE
Support multi-arch image

### ISSUE THREAD

**Issue by cyb70289** [kubernetes-csi/external-provisioner#381]
Current csi-provisioner image is only for x86(same for other projects under kubernetes-csi).
It makes it hard to deploy k8s storage cluster on other architectures like Arm.

It's better to build multi-arch image which works seamlessly on both Arm and x86. Similar job has been started on cephcsi project. As cephcsi depends on k8scsi containers, we would like to add multi-arch support to k8scsi containers too.

**Comment by Madhu-1** [comment]
cc @pohly @msau42

**Comment by leakingtapan** [comment]
What's the plan for this? Preferably, I need multi-arch images on quay.io for other csi sidecars as well. After I x-compiled the ebs csi to arm, but then realize it's side cars are still in x86

**Comment by pohly** [comment]
See https://github.com/kubernetes-csi/csi-release-tools/issues/86.

In short, upcoming releases will be multi-arch. There are no plans at this point to backport the build changes to older, existing releases.

**Comment by RobReus** [comment]
@leakingtapan we at https://github.com/raspbernetes/multi-arch-images are all about ARM64 (and others) support for popular images like these. Take a look, maybe it's useful for you :)

**Comment by cyb70289** [comment]
FWIW, [this patch](https://github.com/kubernetes-csi/csi-release-tools/pull/91) enables Arm64 in csi-release-tools, which is used by all k8s-csi projects to build/publish images. csi-release-tools code is synced at next release of each k8s-csi project.
Multiarch images are not pushed to quay.io. Per my knowledge, they are located at [gcr.io](https://gcr.io/k8s-staging-csi).

**Comment by cyb70289** [comment]
Close this issue as it's not necessary to enable multi-arch for each csi project.
