### ISSUE TITLE
Arg "--enable-leader-election" is not consistent with other sidecars

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-provisioner#401]
All the other sidecars use "--leader-election".

**Comment by Madhu-1** [comment]
@msau42 current default leader election type is Endpoints https://github.com/kubernetes-csi/external-provisioner/blob/master/cmd/csi-provisioner/csi-provisioner.go#L68 to make it consistent with other sidecars are we planning to make default as leases and remove this flag?
