### ISSUE TITLE
frequently switching leader when dynamically provisioning many PV objects at the same time

### ISSUE THREAD

**Issue by k2huang** [kubernetes-csi/external-provisioner#416]
In our k8s cluster, we maybe need dynamically provision many PV objects at the same time via csi-provisioner. So I adjusted its boot option <--worker-threads>, but I found the leader election goroutine can't work well sometimes, and frequently switching the leader among multiple csi-provisioner copies.

After checking code, I noticed there is no way to adjust the throttle value for clientset, and its default value is so small:
```go
    // QPS indicates the maximum QPS to the master from this client.
    // If it's zero, the created RESTClient will use DefaultQPS: 5
    QPS float32
    // Maximum burst for throttle.
    // If it's zero, the created RESTClient will use DefaultBurst: 10.
    Burst int
```
And this value will be shared between leader election goroutine and new PV Object creation goroutines. If new PV Object creation goroutines consume a lot, leader election goroutine will be affected.  
Can we export boot option for clientset throttling, such as <--kube-api-burst> and <--kube-api-qps> or create different clientset instances for  leader election goroutine and new PV Object creation goroutines?

**Comment by RaunakShah** [comment]
Configuring QPS and Burst definitely seems productive. We have seen throttling in scale tests as well. @xing-yang if we're okay with that approach, i can create a PR to add two new flags for configuring QPS and Burst (and possibly set the default to higher than 5?).

**Comment by xing-yang** [comment]
@RaunakShah Yes, that makes sense.  In addition, can you see if it is possible to create 2 different clientset instances for leader election goroutine and PV creation/deletion goroutines?

**Comment by RaunakShah** [comment]
Sounds good! Will open a PR soon
