### ISSUE TITLE
Optimize CreateVolume from PVC as source, to not create and delete a volume, when source PV(C) is smaller than the request

### ISSUE THREAD

**Issue by ShyamsundarR** [kubernetes-csi/external-provisioner#417]
When cloning from a PVC source, we have checks to ensure the request is not smaller than the PVC source [1] and error out if so.

When the PVC request is larger than the source PV(C), we go ahead and create/request the clone, but post creation check if the response size is smaller than the request [2] and call DeleteVolume.

Typically (or always), if the source PV(C) size is smaller than the request, a clone will have a smaller size than its request. This leads to wasteful Create->Delete volume calls.

Instead of the above, if we added required checks on the size prior to creating the smaller volume from source, it would be optimal.

Are there any gotchas because of which for clone from PVC does not have such checks?

[1] Size check for smaller request than source PVC: https://github.com/kubernetes-csi/external-provisioner/blob/efcaee79e47446e38910a3c1a024824387fcf235/pkg/controller/controller.go#L792-L798
[2] DeleteVolume call on detecting response size is less than request: https://github.com/kubernetes-csi/external-provisioner/blob/efcaee79e47446e38910a3c1a024824387fcf235/pkg/controller/controller.go#L624-L632

**Comment by xing-yang** [comment]
Requested volume size is already passed into the CSI driver's CreateVolume function.  It is CSI driver's responsibility to make sure the created volume indeed has the requested size by setting the size in CreateVolumeResponse.  The provisioner is doing the right check by making sure the CSI driver has created a volume of the requested size.

**Comment by ShyamsundarR** [comment]
> Requested volume size is already passed into the CSI driver's CreateVolume function. It is CSI driver's responsibility to make sure the created volume indeed has the requested size by setting the size in CreateVolumeResponse. The provisioner is doing the right check by making sure the CSI driver has created a volume of the requested size.

Reading the spec again, and specifically the `CapacityRange` [text](https://github.com/container-storage-interface/spec/blob/da3002f2908656e6387aa91d72ac77441900b974/lib/go/csi/csi.pb.go#L753-L759), I understand the following,
- a well implemented CSI plugin, will fail the CreateVolume call based on the request size being larger than the possible response, when it cannot internally expand the volume to the requested size (or other related reasons)
- will expand the volume to the requested size when possible and return a success

The checks in the code is for when this is not honored by the plugin.

Closing this issue based on the spec verbiage and understanding above. Thanks!
