### ISSUE TITLE
cloning of volumesinuse has not enforced by the api/sidecar. 

### ISSUE THREAD

**Issue by humblec** [kubernetes-csi/external-provisioner#437]
From the cloning documentation: (https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/)

```The implementation of cloning, from the perspective of the Kubernetes API, simply adds the ability to specify an existing PVC as a dataSource during new PVC creation. The source PVC must be bound and available (not in use).```

As per the above, the source PVC must be **`bound and `available(not in use)`**.  

Is it the case that, **`not in use`** is an enforcement happening from API server or from sidecar? or this has to be handled by SP in their driver implementation?  AFAICT, this check is not performed either in the API server or sidecar.  Is it deliberate or a bug? If the latter ( it has to be implemented by the sp driver) is the solution we recommend we should improve the documentation and possibly share a method to achieve the same. 

Additional details:

The`volumeInUse` field is available in `NodeStatus object`. Making use of this field to block or unblock the request from a plugin driver may not be easy.

**Comment by msau42** [comment]
I believe the intent of the wording here was for the user to make sure it's not in use, similarly to how snapshots works. @j-griffith maybe the wording should be modified to make that more explicit. Also I think we should avoid saying "available" to not confuse it with the PV phase "available".

**Comment by xing-yang** [comment]
Agree with @msau42.

**Comment by j-griffith** [comment]
@msau42 @humblec Yes, I agree I can fix up that wording.  As I recall we intentionally left it as a "recommend" and not an enforcement on our side because there are a good number of backends that "aren't impacted" or don't care so to speak.

My thought is remove the "not in use" and "available" part as you suggest, but also perhaps update the CSI Plugin docs to point out that depending on a plugins capabilities and behaviors the plugin may want to check these things when receiving a clone request?

**Comment by humblec** [comment]
> I believe the intent of the wording here was for the user to make sure it's not in use, similarly to how snapshots works. @j-griffith maybe the wording should be modified to make that more explicit. Also I think we should avoid saying "available" to not confuse it with the PV phase "available".

True. The `available` part can invite confusion. But, I am wondering what we wanted to say/were trying to convey in the first place by `available` with the mention in the current documentation? 

Are we concluding that, the PVC should be `BOUND` and that's the only requirement? 

@j-griffith IMO, removing **`in use`** would cause more confusion and can invite more issues in a cluster. If we do so, the user is free to perform or try the clone/snapshot operation without any checks/restrictions. I don't think SP has a mechanism now to advertise whether the clone is supported when volume in use or NOT supported in use volumes. Am I missing something? If there is no mechanism from the plugin to advertise, I think we have to be careful. Especially when we know that,  the current snapshot mechanism doesn't have any guarantee in data consistency. We should try to narrow the damage as much as we can as an ecosystem.

**Comment by msau42** [comment]
To be more clear and consistent with how we worded the snapshots behavior, we can provide a warning that the user needs to ensure data consistency on the source volume before taking a clone.

**Comment by humblec** [comment]
sending a PR to fix this.
