### ISSUE TITLE
failed to provision volume with StorageClass "gce-fast-regional": rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by ajaykmis** [kubernetes-csi/external-provisioner#462]
Hi, 

I am trying to create a PVC from a VolumeSnapshot in GKE 1.17. but the PVC always fails the first time - with the error : 
Warning  ProvisioningFailed     3s                 pd.csi.storage.gke.io_gke-3292dc0cc953259ae863-6e51-ee44-vm_49f3a555-6e32-44d2-b129-36dc0b8c3a00  failed to provision volume with StorageClass "gce-fast-regional": rpc error: code = DeadlineExceeded desc = context deadline exceeded

It eventually succeed, but I am trying to understand why it failed the first time. 
  Type     Reason                 Age                From                                                                                              Message
  ----     ------                 ----               ----                                                                                              -------
  Normal   WaitForFirstConsumer   16s (x2 over 28s)  persistentvolume-controller                                                                       waiting for first consumer to be created before binding
  Warning  ProvisioningFailed     3s                 pd.csi.storage.gke.io_gke-3292dc0cc953259ae863-6e51-ee44-vm_49f3a555-6e32-44d2-b129-36dc0b8c3a00  failed to provision volume with StorageClass "gce-fast-regional": rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  ProvisioningFailed     3s                 pd.csi.storage.gke.io_gke-3292dc0cc953259ae863-6e51-ee44-vm_49f3a555-6e32-44d2-b129-36dc0b8c3a00  failed to provision volume with StorageClass "gce-fast-regional": rpc error: code = Aborted desc = An operation with the given Volume ID projects/miao-miao-miao-dev/regions/us-west1/disks/pvc-adee6f05-6f86-44f7-aab9-db3f6cf727a6 already exists
  Normal   Provisioning           2s (x3 over 13s)   pd.csi.storage.gke.io_gke-3292dc0cc953259ae863-6e51-ee44-vm_49f3a555-6e32-44d2-b129-36dc0b8c3a00  External provisioner is provisioning volume for claim "build/restored-pvc"
  Normal   ExternalProvisioning   1s (x2 over 13s)   persistentvolume-controller                                                                       waiting for a volume to be created, either by external provisioner "pd.csi.storage.gke.io" or manually created by system administrator
  Normal   ProvisioningSucceeded  1s                 pd.csi.storage.gke.io_gke-3292dc0cc953259ae863-6e51-ee44-vm_49f3a555-6e32-44d2-b129-36dc0b8c3a00  Successfully provisioned volume pvc-adee6f05-6f86-44f7-aab9-db3f6cf727a6

This is on GCP cluster running "1.17.9-gke.600". I am using regional-pd as a replication type in my storage class. 

Appreciate the help.

**Comment by msau42** [comment]
Issue was addressed in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/576
/close
