### ISSUE TITLE
storage capacity: scalability of pkg/capacity/topology/nodes.go

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/external-provisioner#466]
For the sake of simplicity, nodes.go uses slice to store all known segments and iterates over all of them to determine whether a new one has to be added.

We need:
- a test benchmark which scales this up to a high number of nodes
- if the slice turns out to be slow, a better data structure:
  - A tree with topology key/value pairs on the edges and the segment with those pairs in the leaf.
  - Serialize the slice in a string, then use that string as key in a map.

A map of segments does not work because a segment is a slice, and slices cannot be used as key in a map.

**Comment by msau42** [comment]
Another consideration for performance, is to check the capacity after every successful provision operation, instead of once a minute, so that the scheduler can use more up to date information

**Comment by pohly** [comment]
> Another consideration for performance, is to check the capacity after every successful provision operation, instead of once a minute, so that the scheduler can use more up to date information

Yes, that's part of the KEP and not implemented yet. However, that's a separate issue.
