### ISSUE TITLE
Orphaned PVs if provisioner gets killed and restarted

### ISSUE THREAD

**Issue by sbezverk** [kubernetes-csi/external-provisioner#47]
Currently there is a check in the provisioner before PV gets deleted for a privisioner ID and if it does not match with the ID of current provisioner PV does not get deleted. While playing for hostpath plugin, I killed and re-created provisioner, as a result provisioner got new ID and refused to delete previous' privisioner created volumes, so bunch of PVs became a sort of orphaned and needed manual deletion.
Maybe we should not check for provisioner identity? What does this check serve for?

**Comment by msau42** [comment]
+1 I'm seeing this issue.  The provisioner ID needs to be persistent across plugin restarts.

**Comment by msau42** [comment]
Nevermind I saw a different issue: https://github.com/kubernetes/kubernetes/issues/65058

I just tested killing the controller pod in these scenarios and DeleteVolume succeeded:
* After VolumeCreate is successful and before PVC is deleted
* After first VolumeDelete was triggered and before the delete operation completed

**Comment by msau42** [comment]
Is this still an issue?
