### ISSUE TITLE
PV Created During Provision has Inaccurate Capacity

### ISSUE THREAD

**Issue by davidz627** [kubernetes-csi/external-provisioner#48]
The capacity of the Persistent Volume should be the size reported by the driver, not the side of the Persistent Volume Claim.

**Comment by sbezverk** [comment]
@davidz627 good catch, `hostpath` plugin did not report back the number of "allocated" bytes at all (fixed now).

**Comment by davidz627** [comment]
glad you found that! I was also referring to an issue in the external provisioner:
https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L253
It pulls capacity for the PV directly from the PVC instead of from the response of the driver. I can submit a PR for this later today.
