### ISSUE TITLE
Restoring from a snapshot to a larger size

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-provisioner#485]
Today, what happens with many block-based plugins is that the disk will be created at the larger size, but the filesystem (from the snapshot) is at the smaller size. Filesystem expansion won't be triggered because PV is created at the requested PVC size.

We discussed this at the csi standup last week and agreed that the behavior should be:
* If a plugin is not going to resize the filesystem during the restore from snapshot operation, then they should return the original snapshot size (the original block size), so that the resize operation can be done.
* If a plugin is going to resize everything as part of restore, including the filesystem, then they should return the new size.
* If the plugin returns nothing (because size is optional today), then we continue the same behavior of setting the pv to the new size regardless.

This bug can track the following aspects:
- [ ] Do we need to clarify anything in the CSI spec?
- [ ] Make sure external-provisioner is doing the right thing, and we have unit tests
- [ ] Update mock driver and add e2e tests for the different scenarios
- [ ] Add generic e2e test that can be used by all plugins

Updating individual csi drivers to return the proper behavior can be tracked separately.

**Comment by msau42** [comment]
/kind bug

cc @jsafrane @gnufied @xing-yang @bswartz

**Comment by msau42** [comment]
Another open issue: should we apply the same logic to clone?

**Comment by msau42** [comment]
cc @j-griffith

**Comment by msau42** [comment]
@Jiawei0227 will help take a look at implementing this

**Comment by gnufied** [comment]
issue @jsafrane created in k/k repo has summary of discussion so far - https://github.com/kubernetes/kubernetes/issues/94929

**Comment by bswartz** [comment]
The text from the CreateVolumeRequest message in the spec says:

 // This field is OPTIONAL. This allows the CO to specify the capacity
  // requirement of the volume to be provisioned. If not specified, the
  // Plugin MAY choose an implementation-defined capacity range. If
  // specified it MUST always be honored, even when creating volumes
  // from a source; which MAY force some backends to internally extend
  // the volume after creating it.
  CapacityRange capacity_range = 2;

The current implication is that any expansions are magically taken care of inside the CreateVolume call. We definitely need spec language here clarifying that while the new size must be honored insofar as the controller's notion of the volume size, the CO may need to do the NodeExpand portion of the work to bring the node's notion of the volume size into sync.

**Comment by j-griffith** [comment]
On the clone side of things we enforced the PVC being created must be >= size of the source.  The plugin should enforce this and not allow a smaller volume to be created.  I don't think clones have this issue because unlike snapshots we're directly linked to the capabilities and size characteristics of the source volume.

I'm happy to double check and make sure there's not a weird corner case here but as I recall the logic is a bit more simple (and restrictive) than snapshots.

**Comment by Jiawei0227** [comment]
There is currently a discussion here: https://github.com/container-storage-interface/spec/pull/452
I will start to implement this as soon as we get the final decision on how the CO and SP should behave.

**Comment by Jiawei0227** [comment]
/remove-lifecycle stale

I am grooming my backlog and found this one. It seems from the last CSI meeting, we decide that to let each CSI driver to handle it. They should call the expand. So I guess there is no more work involved in the csi-provisioner for now?

**Comment by xing-yang** [comment]
> I am grooming my backlog and found this one. It seems from the last CSI meeting, we decide that to let each CSI driver to handle it. They should call the expand. So I guess there is no more work involved in the csi-provisioner for now?

Yes. CSI driver needs to handle this.  @jsafrane has updated the CSI spec PR: https://github.com/container-storage-interface/spec/pull/452

**Comment by xing-yang** [comment]
Reopen this so that CSI driver maintainers are aware of this issue.

**Comment by humblec** [comment]
@msau42 @xing-yang @jsafrane afaict, this is handled in provisioner code already and I am closing this issue. Please reopen if required.
/close

**Comment by amacaskill** [comment]
@humblec Could you please point to where in the provisioner code this is handled?

**Comment by msau42** [comment]
@amacaskill the conclusion of this bug is that each CSI driver needs to make changes to their NodeStage/NodePublish implementations to resize the filesystem if possible. See https://github.com/container-storage-interface/spec/pull/452/files for the spec clarification and https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/595/files for an example. Resize utilities have been exported in https://github.com/kubernetes/kubernetes/pull/99088/files so that CSI drivers can share similar logic.

For pd csi driver it looks like it was added in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/972

**Comment by humblec** [comment]
@amacaskill addition to what @msau42 mentioned above,  this make sure the controller allows to have a capacity >= snapshot ->restore size. https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L1134
