### ISSUE TITLE
Support  secret in NodeExpansion Call.

### ISSUE THREAD

**Issue by humblec** [kubernetes-csi/external-provisioner#499]
In different use cases we need "secret" passed to the CSI driver to perform NodeExpansion which is missing atm . One of the very visible use case is that, the expansion on LUKS enabled device, which needs the passphrase in order to resize the device on the node.

One other use case is that, at times we need to check the actual size of the image ( for ex: RBD image size in Ceph Cluster) before proceeding on FS resize to avoid false positive returns on fs resize operation. For that we have to connect to the backend cluster which need secret in the request.

Reference#
CSI spec issue # container-storage-interface/spec#445
CSI spec PR # container-storage-interface/spec#457
k/k issue # https://github.com/kubernetes/kubernetes/issues/95367

**Comment by msau42** [comment]
/assign @gnufied 
to followup on this.

**Comment by humblec** [comment]
@gnufied considering `CSI Spec 1.5` carry the capability, can we get support here too?  please feel free to assign this to me if you are busy with other tasks.
