### ISSUE TITLE
topology placement for statefulset

### ISSUE THREAD

**Issue by zetaab** [kubernetes-csi/external-provisioner#517]
I have use case that i do have 3 AZs (both compute and volume). I also have statefulset with 3 replicas. What I want is place one replica per zone to have highly availability for the service. However, it creates volumes randomly to these zones. Which component is the correct one which have the logic where these are created? 

Currently it creates following:
- 1 pvc for zone-1
- 2 pvc for zone-2
- 0 pvc for zone-3

What I want is:
- 1 pvc for zone-1
- 1 pvc for zone-2
- 1 pvc for zone-3

in legacy provisioners this was handled in k8s core code, but no idea does such feature exist yet in csi provisioner? Anyways that is kind of must have.

**Comment by pohly** [comment]
You can use a storage class with late binding, then PVCs have a higher chance of being created where the pods are about to run.

https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode
