### ISSUE TITLE
New feature to skip affinity in provisioner

### ISSUE THREAD

**Issue by zetaab** [kubernetes-csi/external-provisioner#520]
We have use case where our compute zone names does not match to volume zone names. When topology support is turned on the provisioning for volumes does not work at all. 

Please read https://github.com/kubernetes/cloud-provider-openstack/issues/1300

**Comment by msau42** [comment]
Sorry I'm not sure I understand the request. If your driver can't support topology, then you need to turn the topology feature gate off.

**Comment by zetaab** [comment]
@msau42 the problem is that topology feature is going to be enabled by default in future. Which means that it will break current setup for instance part of openstack users.

Driver do support that, but the openstack setups in some companies does not.

**Comment by msau42** [comment]
I think it would be best to work with the openstack/cinder csi driver to make sure they can properly support topology for your scenario or make topology optional. It sounds like openstack supports some topologies that the csi driver is not properly handling.

**Comment by zetaab** [comment]
yeah, so basically openstack cinder csi plugin should be able to say "I am not supporting topologies", if there is weird zone setup between nodes and volume zones.
