### ISSUE TITLE
CSI and Local Volume

### ISSUE THREAD

**Issue by nevermore-muyi** [kubernetes-csi/external-provisioner#525]
Hi, it's there any plans for csi and local volume? Just as the follow talks:
https://github.com/kubernetes-retired/external-storage/issues/824
thanks.
@cofyc @pohly

**Comment by pohly** [comment]
Quite a bit is going on regarding that:
- provisioning: https://github.com/kubernetes-csi/external-provisioner/issues/487
- storage capacity: https://github.com/orgs/kubernetes-csi/projects/32
- inline, ephemeral volumes: https://github.com/orgs/kubernetes-csi/projects/34

**Comment by ruanchen** [comment]
@pohly maybe we can use the idea from [topolvm](https://github.com/topolvm/topolvm),use a crd for proxy, provisioner and csi driver interact with the crd.
Just as the blog describes: https://blog.kintone.io/entry/topolvm.

**Comment by pohly** [comment]
I'm familiar with TopoLVM. I think the extension that I am planning for external-provisioner will be simpler (no need for extra CRDs, less code).

**Comment by ruanchen** [comment]
@pohly Excuse me and can you describe the next step plan about this?
Is the plan like this?
1. external-provisioner deploy on each node
2. use _storage capacity_ for volume dynamic provisioning

**Comment by ruanchen** [comment]
And which release version (kubernetes and csi) we can see the new feature?

**Comment by pohly** [comment]
That's indeed the plan.

Deploying external-provisioner on each node is meant to go into the next external-provisioner release for Kubernetes 1.20.

Storage capacity tracking remains as alpha in 1.20. I hope to get it to beta in 1.21.

**Comment by ruanchen** [comment]
@pohly thank you, look forward to the new feature.

**Comment by ruanchen** [comment]
@pohly Except external-provisioner, resizing and snapshot are also need considered in the future.

**Comment by pohly** [comment]
I only plan to work on external-provisioner. Someone else will have to look into resizing and snapshotting.

**Comment by pohly** [comment]
For the other components:
- https://github.com/kubernetes-csi/external-snapshotter/issues/484
- https://github.com/kubernetes-csi/external-resizer/issues/142

For external-provisioner we are done.

/close
