### ISSUE TITLE
storage capacity: scheduler consistency

### ISSUE THREAD

**Issue by nevermore-muyi** [kubernetes-csi/external-provisioner#545]
In current version, scheduler just get the free capacities of **StorageCapacity**, but do not update the scheduler cache, which may lead to scheduling inconsistencies. So, i think scheduler should cache the storage capacities in reverse step as assume pod.
@pohly

**Comment by pohly** [comment]
I'm not sure I understand what you mean with "should cache the storage capacities". Can you elaborate?

Are you suggesting that the scheduler should track in-flight volumes and somehow model how that affects available capacity? That was discussed at length already, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1472-storage-capacity-tracking#no-modeling-of-storage-capacity-usage and https://github.com/container-storage-interface/spec/issues/301

**Comment by ruanchen** [comment]
Yes, what you describe is my think, thanks.

**Comment by pohly** [comment]
@nevermore-muyi: so can we close this issue here?

**Comment by nevermore-muyi** [comment]
ok, i close the issue.
