### ISSUE TITLE
volume leaks when PVC is deleted when associated PV is in the terminating state

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes-csi/external-provisioner#546]
Steps

1. Create PVC and wait for it to get bound.

```
# kubectl create -f pvc.yaml 
persistentvolumeclaim/example-vanilla-block-pvc created
```

```
# kubectl get pvc
NAME                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS               AGE
example-vanilla-block-pvc   Bound    pvc-6791fdd4-5fad-438e-a7fb-16410363e3da   5Gi        RWO            example-vanilla-block-sc   19s
```

```
# kubectl get pv pvc-6791fdd4-5fad-438e-a7fb-16410363e3da
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                               STORAGECLASS               REASON   AGE
pvc-6791fdd4-5fad-438e-a7fb-16410363e3da   5Gi        RWO            Delete           Bound    default/example-vanilla-block-pvc   example-vanilla-block-sc            23s
```

2. Delete PV.

```
# kubectl delete pv pvc-6791fdd4-5fad-438e-a7fb-16410363e3da
persistentvolume "pvc-6791fdd4-5fad-438e-a7fb-16410363e3da" deleted
^C
```

PV can not be deleted, so `kubectl delete  pv` command is not giving up terminal prompt. So I typed `ctl+c` to exit.
Checked PV status. It went into terminating state.

```
# kubectl get pv pvc-6791fdd4-5fad-438e-a7fb-16410363e3da
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                               STORAGECLASS               REASON   AGE
pvc-6791fdd4-5fad-438e-a7fb-16410363e3da   5Gi        RWO            Delete           Terminating   default/example-vanilla-block-pvc   example-vanilla-block-sc            2m23s
```

3. When PV is in the terminating state, delete PVC.

```
# kubectl delete pvc example-vanilla-block-pvc
persistentvolumeclaim "example-vanilla-block-pvc" deleted
```

4. PV and PVC are both deleted from the system.

```
# kubectl get pv pvc-6791fdd4-5fad-438e-a7fb-16410363e3da
Error from server (NotFound): persistentvolumes "pvc-6791fdd4-5fad-438e-a7fb-16410363e3da" not found
```

The controller is not getting calls to delete the volume from the datastore. This results into leaking volume on the datastore.

Above workflow is executed using very latest external-provisioner - `v2.1.0`. This issue is also present on prior release of the external provisioner.

Filing this bug to discuss about what fix we can make to prevent this orphan volume on the system.

This issue was also discussed here - https://github.com/kubernetes-csi/external-provisioner/issues/195#issuecomment-542630722

cc: @xing-yang @SandeepPissay

**Comment by xing-yang** [comment]
> The controller is not getting calls to delete the volume from the datastore

@divyenpatel Which controller?  You meant the CSI Driver controller?

**Comment by pohly** [comment]
My take on this: the system works as designed at the moment. Admins should only delete a PV if they know that the underlying volume in the storage system is gone.

The PV protection controller only prevents that the PV object gets removed while there is a PVC that uses the PV. It has no knowledge about the underlying volume.

**Comment by divyenpatel** [comment]
> > The controller is not getting calls to delete the volume from the datastore
> 
> @divyenpatel Which controller? You meant the CSI Driver controller?

Yes

**Comment by xing-yang** [comment]
The Reclaim Policy on PV is "Delete" here. If volume is not deleted regardless of the Reclaim Policy, what is the difference between "Delete" and "Retain" in this case?

**Comment by xing-yang** [comment]
Discussed in today's sig-storage meeting.

* Work as expected but very confusing as behavior changes depending on whether PV is being deleted before PVC is deleted.
If we fix this, it will break existing customers with workflow that depends on this behavior (@jsafrane).
* Should update the doc first: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming. Then look at how to fix this without breaking existing customers workflows.

**Comment by wjun** [comment]
IHAC who met this issue in their production environment. My customer provides k8s as a self service to its customers. In this service provider model, whatever change customers make to their clusters through valid k8s CL/APIs, the service provider should not have potential billing issues (they count disk usages into billing).

**Comment by xing-yang** [comment]
Discussed this with @jsafrane and @msau42.  We could introduce an alpha feature in 1.22 and fix the code to always honor the deletion policy, in the same time, deprecate the existing behavior.  After one year (4 releases), we can GA the feature and stop supporting the existing behavior.

**Comment by xing-yang** [comment]
CC @deepakkinni

**Comment by pohly** [comment]
/reopen

Not fixed in external-provisioner yet, only in sig-storage-lib-external-provisioner.

**Comment by igoratencompass** [comment]
Interesting, thought this was a security feature so you don't delete a PV by accident while still referenced by a PVC.
