### ISSUE TITLE
Errors from fetching secrets should be reported

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/external-provisioner#55]
The provisioner only logs error when it fails to fetch a secret configured in StorageClass and continues with provisioning. It should return error to the user instead.

Secrets are optional in CSI, however admin really wants them to be used once he configures them in StorageClass. If there is a typo in secret name, admin should know and provisioning should fail. Nobody knows what a CSI driver will do with no secret, it may provision a volume that's accounted to another team / department than the admin wants to.

**Comment by saad-ali** [comment]
Seems reasonable to me.
This will need to be changed on kubernetes as well. @jsafrane could you open an issue to track this.
