### ISSUE TITLE
Forget TranslateInTreeStorageClassToCSI in Delete.

### ISSUE THREAD

**Issue by huchengze** [kubernetes-csi/external-provisioner#552]
https://github.com/kubernetes-csi/external-provisioner/blob/637608cab7d37ddef0575fa2191ba22c57e43cc2/pkg/controller/controller.go#L1094

After writing the rbd-csi migration code, I tested it on my own cluster.
Provision successed, but Delete failed.
Then I realized that there is no TranslateInTreeStorageClassToCSI in Delete.
I will create a PR for this.

**Comment by Jiawei0227** [comment]
Thanks! This is really good finding! Can you rebase the PR?

**Comment by Jiawei0227** [comment]
Hey @huchengze , can you also mention a little more details on what specific parameter need to be transferred? Why will it fail without translate storage class?

**Comment by Jiawei0227** [comment]
I quickly checked the gce-pd, aws, azuredisk csi-translation-lib implementation and did not find there are anything special that need to be translated other than topology. Is  rbd-csi somehow have different implementation?

**Comment by huchengze** [comment]
> I quickly checked the gce-pd, aws, azuredisk csi-translation-lib implementation and did not find there are anything special that need to be translated other than topology. Is rbd-csi somehow have different implementation?

https://github.com/kubernetes-csi/external-provisioner/blob/5d250e590f683b94bfca4c4dfb5260ad3633542b/pkg/controller/controller.go#L1149

This func in delete need to get `provisionerSecretParams`, which is:

https://github.com/kubernetes-csi/external-provisioner/blob/5d250e590f683b94bfca4c4dfb5260ad3633542b/pkg/controller/controller.go#L152-L158

For some csi plugins like gce-pd, aws, or azuredisk, they may don't need a secret to save their credentials. But other plugins like rbd need.

https://github.com/kubernetes/kubernetes/blob/16b909ce1483258464715c9ab76b4dff82d596e5/pkg/volume/rbd/rbd.go#L634-L637

So the func TranslateInTreeStorageClassToCSI for rbd will change `adminsecretname` to `csiProvisionerSecretName` and `adminsecretnamespace` to `csiProvisionerSecretNamespace`,  then csi-provisioner can get the credentials of rbd and pass it to rbd-csi.

But without TranslateInTreeStorageClassToCSI, there are no `provisionerSecretParams` in in-tree rbd sc, so that rbd-csi can't delete success.

**Comment by msau42** [comment]
It looks like in-tree rbd plugin is depending on StorageClass for DeleteVolume, which is an unfortunate anti-pattern we have been discouraging: https://github.com/kubernetes/kubernetes/blob/16b909ce1483258464715c9ab76b4dff82d596e5/pkg/volume/rbd/rbd.go#L570

We also have an outstanding issue to get rid of CSI's dependency on StorageClass for deletion secrets: https://github.com/kubernetes-csi/external-provisioner/issues/330

But it looks like we will still need to support this for backwards compatibility.

**Comment by huchengze** [comment]
> It looks like in-tree rbd plugin is depending on StorageClass for DeleteVolume, which is an anti-pattern we have been discouraging: https://github.com/kubernetes/kubernetes/blob/16b909ce1483258464715c9ab76b4dff82d596e5/pkg/volume/rbd/rbd.go#L570
> 
> We also have an outstanding issue to get rid of CSI's dependency on StorageClass for deletion secrets: #330
> 
> But it looks like we will still need to support this for backwards compatibility.

Yes, maybe finilly we will find a way to

**Comment by huchengze** [comment]
> It looks like in-tree rbd plugin is depending on StorageClass for DeleteVolume, which is an anti-pattern we have been discouraging: https://github.com/kubernetes/kubernetes/blob/16b909ce1483258464715c9ab76b4dff82d596e5/pkg/volume/rbd/rbd.go#L570
> 
> We also have an outstanding issue to get rid of CSI's dependency on StorageClass for deletion secrets: #330
> 
> But it looks like we will still need to support this for backwards compatibility.

Yes, by #567 some intree plugins like rbd will find a way to get their credentials for DeleteVolume and it won't affect other plugins.

**Comment by Jiawei0227** [comment]
Hey Chengze, I am wondering if you are working on CSI migration for ceph drivers?

If you are, it would be really nice if you can update some status on that.

https://docs.google.com/document/d/1j6uF9sOoGCQ9nNFVrdvCWyn77o9k3-758qsEj2K3BAY/edit#heading=h.qgo2lkk8gkqp

**Comment by huchengze** [comment]
@Jiawei0227 
It looks like there are no plans to migrate in-tree ceph driver.
https://github.com/ceph/ceph-csi/issues/1725
I have tried to do it, but it needs a lot code changing in ceph-csi and I'm not sure they can accept that.

**Comment by Jiawei0227** [comment]
oh, okay. I saw you were testing rbd so I thought you are working on that. It's okay.
