### ISSUE TITLE
Make release with latest translation-lib

### ISSUE THREAD

**Issue by mattcary** [kubernetes-csi/external-provisioner#563]
Should happen before 1.21 release.

https://github.com/kubernetes/kubernetes/pull/97823 has the changes we want.

/cc @Jiawei0227

**Comment by pohly** [comment]
https://github.com/kubernetes-csi/external-provisioner/pull/564 should also be included in that release.

**Comment by mattcary** [comment]
Also the new metrics, https://github.com/kubernetes-csi/csi-lib-utils/pull/77.

**Comment by chrigl** [comment]
https://github.com/kubernetes/kubernetes/pull/98311 would be great as well. It is already on release-1.20 (not tagged yet) and tag v1.21.0-alpha.3.

**Comment by andyzhangx** [comment]
@msau42 @Jiawei0227 could you help release `2.1.1` version, it has one critical csi migration fix, thanks.

**Comment by Jiawei0227** [comment]
@andyzhangx I will create a release-note after https://github.com/kubernetes-csi/external-provisioner/pull/567 being merged tomorrow.

**Comment by pohly** [comment]
Can we also get https://github.com/kubernetes-csi/external-provisioner/pull/565 included?

**Comment by pohly** [comment]
It looks like v2.1.0 was tagged on master and all changes since then are bug fixes for a v2.1.1 release or build fixes that we need to test that release on Kubernetes 1.20:
https://github.com/kubernetes-csi/external-provisioner/compare/v2.1.0...master

I would be okay to just tag v2.1.1 on master. We can also create a release-2.1 branch, it just would be identical to master for now.

**Comment by msau42** [comment]
I will create a release branch so that we're consistent in our release process. I think the release-notes tool doesn't support patch releases on master branch when using a discover method.

**Comment by msau42** [comment]
release-2.1 is created. I took everything up until (not including) https://github.com/kubernetes-csi/external-provisioner/pull/560 as that change potentially requires action from consumers of migrated plugins.

For any bug fixes after that https://github.com/kubernetes-csi/external-provisioner/compare/release-2.1...master, please open a cherry-pick PR

**Comment by pohly** [comment]
Here's the one I care about: https://github.com/kubernetes-csi/external-provisioner/pull/568

**Comment by ialidzhikov** [comment]
I think this issue can be closed as new releases that vendor the latest csi-translation-lib were cut - v2.1.1, v2.2.0.

**Comment by pohly** [comment]
/reopen

https://github.com/kubernetes-csi/external-provisioner/pull/621 is still pending?
