### ISSUE TITLE
Is it possible to add custom plugin in csi provisioning flow?

### ISSUE THREAD

**Issue by asifdxtreme** [kubernetes-csi/external-provisioner#570]
Usecase : A data management framework wants to add intelligence or tweak the provisioning before the external-provisioner sends the request to csi driver for provisioning of the pv/pvc.

Solution : ???

Suggestion : 
1. Following the priniciples of extensible code, we can add the options of dynamic plugin which when enabled calls the custom bussiness code before the sending the request to csi driver for provisioning.
2. Provide a feature via arguments which when enabled calls the new sidecar(provided by framework) to do the business logic before provisioning over [here]( https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L500)

**Comment by pohly** [comment]
Other solutions:
- fork the external-provisioner and implement your changes in the fork
- implement a proxy which accepts gRPC calls on a Unix domain socket, acts on those it cases about (CreateVolume?) and then sends them on to the actual CSI driver: external-provisioner -> proxy -> CSI driver

**Comment by msau42** [comment]
What kind of modifications do you want to make to the provisioning request? Can a mutating webhook address your use case? Or is this a use case for the data populator feature?
