### ISSUE TITLE
Why PVC Selector is not support in dynamic provisioning

### ISSUE THREAD

**Issue by mowangdk** [kubernetes-csi/external-provisioner#574]
/kind design

little confused about this part in ```pkg/controller/controller.go```

```
if claim.Spec.Selector != nil {
	return nil, controller.ProvisioningFinished, fmt.Errorf("claim Selector is not supported")
}
```

my question is why Selector is forbidden in provisioning and can I make this error message more detailed?

**Comment by msau42** [comment]
Claim selector is used to filter the available set of PVs to bind to a PVC. This is for the situation where you have precreated PVs in the system that you want to use, not for dynamic provisioning.

What is the use case that you have for using a selector with dynamic provisioning?

**Comment by mowangdk** [comment]
> Claim selector is used to filter the available set of PVs to bind to a PVC. This is for the situation where you have precreated PVs in the system that you want to use, not for dynamic provisioning.
> 
> What is the use case that you have for using a selector with dynamic provisioning

IMHO, Warning event can be thrown instead of blocking dynamic provisioning.

The scene is migrated from flexvolume to csi。
