### ISSUE TITLE
Update VolumeSnapshot API to v1

### ISSUE THREAD

**Issue by chrishenzie** [kubernetes-csi/external-provisioner#602]
The external-provisioner currently uses the v1beta1 API. We should update this to start using the v1 API and mark this feature as GA in the next release.

**Comment by msau42** [comment]
cc @xing-yang 

Also for this upcoming release, let's add a deprecation notice for the snapshot v1beta api.

**Comment by chrishenzie** [comment]
Fixed by https://github.com/kubernetes-csi/external-provisioner/pull/650

/close
