### ISSUE TITLE
distributed provisioning: random failures for immediate binding + AllowedTopologies

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/external-provisioner#611]
Enabling topology tests in csi-driver-host-path led to random test failures for `External Storage [Driver: hostpath.csi.k8s.io] [Testpattern: Dynamic PV (immediate binding)] topology should provision a volume and schedule a pod with AllowedTopologies`.

The smoking gun is this event:
```
Apr 15 23:17:54.837: INFO: At 2021-04-15 23:13:00 +0000 UTC - event for pvc-plnph: {hostpath.csi.k8s.io_csi-hostpathplugin-dqmvv_a6875f50-3875-4081-bdbe-dc75bc843d42 } ProvisioningFailed: failed to provision volume with StorageClass "topology-7135-e2e-sc54m8h": error generating accessibility requirements: selected node '"csi-prow-worker2"' topology 'map[topology.hostpath.csi/node:csi-prow-worker2]' is not in allowed topologies: [map[topology.hostpath.csi/node:csi-prow-worker]]
```

What happened is that the test randomly picked one of the two worker nodes, `csi-prow-worker`, for AllowedTopologies in the test storage class, but then that field was ignored when the different provisioners determined who should provision the volume. The provisioner on `csi-prow-worker2` became the owner, but it then ran into the internal error about "generating accessibility requirements" quoted above. That causes the PVC to become stuck.

It's debatable whether such an internal error should cause the affected provisioner to retry or given up ownership of the PVC. I think such errors should not occur and therefore I wouldn't introduce special behavior for them, i.e. keep retrying.

The fix will be to check AllowedTopologies and ignore PVCs with incompatible topology.

**Comment by verult** [comment]
Is the reason why the error shouldn't occur because we don't expect anyone to set an AllowedTopologies, use immediate binding, and use distributed provisioning?

IMO it's better to skip the test than to remove the provision failed error and fail silently.

**Comment by pohly** [comment]
Provisioning will work, it just has to be attempted on a node that matches the storage class.

**Comment by verult** [comment]
ACK got it, and the fix will make sure a provisioner that doesn't live in a node matching AllowedTopologies will never process the PVC, which is probably better than the provisioner processing the PVC realizing it doesn't belong and then gives up ownership. Thanks!
