### ISSUE TITLE
Error collecting metrics with migratable CSI driver

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/external-provisioner#619]
When used with migratable CSI driver, such as `ebs.csi.aws.com`, the external-provisioner v2.2.0 returns 500 response on its metrics endpoint:

```
$ curl -v localhost:8202/metrics
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8202 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8202 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:8202
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 04 May 2021 16:20:47 GMT
< Content-Length: 243
< 
An error has occurred while serving metrics:

gathered metric family process_start_time_seconds has help "[ALPHA] Start time of the process since unix epoch in seconds." but should have "Start time of the process since unix epoch in seconds."
```

**Comment by pohly** [comment]
Does that only occur with a migratable CSI driver (whatever that is - I don't know), or is that just where you observed it?

**Comment by pohly** [comment]
The error itself comes from registering `process_start_time_seconds` twice, once through the Kubernetes framework, once directly. Here we intentionally disable it to avoid this:
https://github.com/kubernetes-csi/external-provisioner/blob/5d1b62aaa38b309e2c845e97efdc24c944fb66d8/cmd/csi-provisioner/csi-provisioner.go#L189-L193

**Comment by pohly** [comment]
And here we don't:
https://github.com/kubernetes-csi/external-provisioner/blob/5d1b62aaa38b309e2c845e97efdc24c944fb66d8/cmd/csi-provisioner/csi-provisioner.go#L217-L225

**Comment by jsafrane** [comment]
It's only for migratable CSI driver, regular hostpath driver works just fine.
