### ISSUE TITLE
handle DeletedFinalStateUnknown

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/external-provisioner#628]
The delete callback may get invoked with an object of type DeletedFinalStateUnknown and should be able to retrieve the UID from the embedded object instead of ignoring the event:

https://github.com/kubernetes-csi/external-provisioner/blob/f71827bfaa87d61de380518a1522b31fa6ff35d0/pkg/controller/controller.go#L379-L383

**Comment by chrishenzie** [comment]
/remove-lifecycle stale

It looks like we can use [similar logic implemented in the external-attacher](https://github.com/kubernetes-csi/external-attacher/blob/v3.2.1/pkg/controller/controller.go#L171-L173) to handle this.
