### ISSUE TITLE
SupportsBlock method does not work

### ISSUE THREAD

**Issue by bells17** [kubernetes-csi/external-provisioner#631]
Hi, currently, block devices can not use because provisionWrapper struct doesn't have SupportsBlock method.
I think this bug probably has occurred when https://github.com/kubernetes-csi/external-provisioner/pull/586 PR was merged.

ref:
- https://github.com/kubernetes-csi/external-provisioner/blob/359a0e068e079bfa79df75db31e03f32d7743b1f/cmd/csi-provisioner/csi-provisioner.go#L482-L483
- https://github.com/kubernetes-csi/external-provisioner/blob/359a0e068e079bfa79df75db31e03f32d7743b1f/pkg/capacity/provision.go#L26-L87

/kind bug

**Comment by pohly** [comment]
My expectation was that if the embedded `controller.Provisioner` instance implements `SupportsBlock`, then the wrapper will also implement that. As you found, that's not how it works - sorry for that!
