### ISSUE TITLE
should never time out from connecting.

### ISSUE THREAD

**Issue by lpabon** [kubernetes-csi/external-provisioner#64]
The container should never time out from connecting to a grpc socket. Currently, if it fails, it just stops trying and the only way to get it back is to restart the container.

It should continue trying forever. Also, on connection failure it should go back to retrying forever.

**Comment by cduchesne** [comment]
I too have noticed this behavior quite frequently in testing

**Comment by msau42** [comment]
This has been addressed with csi-lib-utils/connection
