### ISSUE TITLE
Make CSI secret handling logic reusable 

### ISSUE THREAD

**Issue by mkimuram** [kubernetes-csi/external-provisioner#653]
CSI secret can be defined as a template as defined [here](https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html#storageclass-secrets). Current implementation of external-provisioner embeds [this logic](https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L1581) in the controller codes as private scoped, which isn't reusable from other controllers.

There are use cases, like PVC transfer and secret protection, to use this logic from other controllers, therefore it needs to be changed to public scoped and move to a kind of util packages.

**Comment by mkimuram** [comment]
@msau42 @jsafrane 

Do you have preference on where the codes should move to?
Is pkg/util in this repo OK or should it be util package in somewhere like https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner ?

**Comment by mkimuram** [comment]
Snapshotter codes seem to [share](https://github.com/kubernetes-csi/external-snapshotter/blob/e6e14c16019ece315f91e8389b08cfcbd07d2e49/pkg/utils/util.go#L287) the same logic with different keys. It looks cleaner to move it to a separate repo. Any thought?

**Comment by msau42** [comment]
https://github.com/kubernetes-csi/csi-lib-utils is the place we've been putting libraries shared by multiple components
