### ISSUE TITLE
Add CSI secret templates as annotation in Provisioned PV

### ISSUE THREAD

**Issue by mkimuram** [kubernetes-csi/external-provisioner#654]
There was a discussion in the meeting on PVC/Snapshot transfer about the model that __operation on PV should not rely on information in StorageClass after PV is provisioned__. The reason for it is that StorageClass can be changed after the PV is provisioned, as a result, the controllers might not rely on the current information in StorageClass.

In the case of PVC transfer, SecretRef in PV may be modified based on the templates after transferred. Therefore, these templates should be kept in PV as annotations.

**Comment by humblec** [comment]
@mkimuram sure, indeed as the discussion went  yesterday, its good to take out the storage class dependency once the pv is provisioned. however I am not sure we were in complete agreement though, especially when the discussion is moving towards transfer of snap vs transfer of pv.

**Comment by xing-yang** [comment]
I thought this is already done and documented here: https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html

Is there anything missing?

**Comment by mkimuram** [comment]
Please see related discussion https://github.com/kubernetes-csi/external-snapshotter/pull/578#discussion_r692079808 .

**Comment by mowangdk** [comment]
I have further questions related with this issue.  

We can upgrade the disk type after provisioned on the fly.  but ```spec.csi.volumeAttributes``` in PersistentVolume is immutable。 How can i fix PersistentVolume type right in this scenario?

@xing-yang @msau42  Any suggestions would really appreciated 🙇
