### ISSUE TITLE
PVC.UID for volume name unique but hard for humans to differentiate

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/external-provisioner#67]
Issue raised by @cduchesne 

With PR https://github.com/kubernetes-csi/external-provisioner/pull/66 the names of the newly provisioned volumes will be based on the UID of the Kubernetes PVC object. Although the UIDs are unique, the UID does not differ much, making it harder for humans to read and differentiate between them.

Example from @cduchesne:
```
[root@prometheus csi-scaleio]# for i in {01..10}; do curl -s http://127.0.0.1:8080/api/v1/namespaces/scaleio/persistentvolumeclaims/vol$i | jq '.metadata.uid'; done
"f151bfd8-3751-11e8-ba9f-0cc47ac6c23c"
"f16e31ee-3751-11e8-ba9f-0cc47ac6c23c"
"f18a35c0-3751-11e8-ba9f-0cc47ac6c23c"
"f1a737cc-3751-11e8-ba9f-0cc47ac6c23c"
"f1c6e464-3751-11e8-ba9f-0cc47ac6c23c"
"f1e6f657-3751-11e8-ba9f-0cc47ac6c23c"
"f2034a06-3751-11e8-ba9f-0cc47ac6c23c"
"f223b1e4-3751-11e8-ba9f-0cc47ac6c23c"
"f2422240-3751-11e8-ba9f-0cc47ac6c23c"
"f25d4bec-3751-11e8-ba9f-0cc47ac6c23c"
```

Since the primary issue here is readability and Kubernetes does the same thing (https://github.com/kubernetes-csi/external-provisioner/pull/66#discussion_r178855141), I would consider this issue low pri. It would be nice if we can come up with a better naming scheme that is deterministicly generated from PVC without collisions.

**Comment by chakri-nelluri** [comment]
+1 for naming based on PVC
For a storage admin, it is impossible to figure out the source of these volumes.

**Comment by saad-ali** [comment]
Was discussing this with @cduchesne some more. He suggested instead of `pvc.uid` we could do `sha256(pvc.uid)` then pull first x characters of the sha https://play.golang.org/p/me6YlbwHhRl

Thoughts?

**Comment by saad-ali** [comment]
One draw back of this is reverse association becomes more difficult.

**Comment by princerachit** [comment]
@cduchesne suggestion sounds good. Focusing on reverse association will result in long name which will cause readability issue. eg. pvc-[sha256(uid)<sub>x chars</sub>]-uid is readable and reversely associated but too long.

**Comment by mcronce** [comment]
To solve the issue of reverse association as well as making it easy for storage admins to quickly figure out where a volume comes from and what it applies to, what are people's thoughts on (either always or with an option) naming the PV something human-readable, e.g. pvc-_namespacename_-_pvcname_?  Including the PVC's namespace and name should guarantee uniqueness.

In case anybody's interested in flavor, my use case is to, with cephfs-backed storage, quickly locate state and configuration for my workloads.

@saad-ali I'm happy to make the changes required for this, but want to get input before just throwing a PR over the fence ;)

**Comment by princerachit** [comment]
@mcronce it is not guaranteed that `pvc-namespacename-pvcname` will give a unique name.
Consider these two pairs of namespace and name:
1. deploy-primary, vol
2. deploy, primary-vol

Both will result in `pvc-deploy-primary-vol`

**Comment by mcronce** [comment]
I have the base functionality I described implemented in https://github.com/mcronce/external-provisioner/commit/4d159a9905ee1abdf226095c37aa8f0699e95c3a - I'd be interested in feedback

I also have a follow-up change in https://github.com/mcronce/external-provisioner/commit/ed716633a36fdedff7ca76dd9f0b94451b52ca6b which, when enabled, makes the entire PV name unique but deterministic based on the PVC namespace and name.  This behavior is nice because with a StorageClass's `reclaimPolicy` set to `Retain`, if a PVC is deleted and recreated it can be reattached to the same piece of storage.  However, the provisioner doesn't seem to do that successfully at this time.  While _I_ would like it, I don't know whether or not that functionality is desired by the community as a whole :)

**Comment by bukzor** [comment]
Isn't there prior art for solving this, in the naming of Deployment pods? A human-readable prefix followed by a uniquifying nonce.  So pvc "my-thing" would result in pv "my-thing-fviwm".

CC: @bulldozier

**Comment by jsafrane** [comment]
PV name should be "computable" from PVC, so multiple provisioners create the same PV name (and get conflict if there are multiple provisioners running accidentally). I am not sure "-fviwm" can be generated from PVC so PVCs with the same name in different namspaces would not conflict - there may be thousands of them and we don't want any conflict here. UID is assigned by the cluster and is guaranteed to be unique.

Deployments/ReplicaSets are easy, if they accidentally start one extra replica they can delete it easily without bad things happening. In PV/PVC case it's harder, we really don't want to loose any data.

**Comment by mcronce** [comment]
@msau42 Thanks!

**Comment by mcronce** [comment]
This is still needed.

**Comment by mcronce** [comment]
This is still an issue :/

**Comment by jsafrane** [comment]
There is https://github.com/kubernetes-csi/external-provisioner/pull/399 that could satisfy most of the use cases noted here.
