### ISSUE TITLE
Why can not re-queue the object if exceed failure limit

### ISSUE THREAD

**Issue by smileusd** [kubernetes-csi/external-provisioner#671]
https://github.com/kubernetes-csi/external-provisioner/blob/d6861307ef31020e93610d9708acc640adbacdcb/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v7/controller/controller.go#L942

I think it is unnecessary to prevent re-queue the failure object. If the object is updated by user or admin like fixed the annotation or spec, It need re-queue and try to handle again.  And if the controller is restart, it will also to handle the failure object it looks like not agreement with the design that the controller want never handle this object again.

**Comment by msau42** [comment]
I agree we should always retry forever. It looks like the library supports setting 0 to mean retry forever, and we are setting it to 0 in external-provisioner:
https://github.com/kubernetes-csi/external-provisioner/blob/master/cmd/csi-provisioner/csi-provisioner.go#L354

Are you seeing different behavior?

**Comment by msau42** [comment]
/close
please reopen if you are seeing different behavior in the csi provisioner
