### ISSUE TITLE
Releases for armv7

### ISSUE THREAD

**Issue by fidesachates** [kubernetes-csi/external-provisioner#691]
Is there a timeline for releasing a new version so we can get the armv7 support? Based on this [comparison](https://github.com/kubernetes-csi/external-provisioner/compare/v2.2.2...release-2.2), I'm guessing just a new release will give us the support in 2.2.x?

This is [blocking ](https://github.com/kubernetes-csi/csi-driver-smb/issues/405)me from using csi-driver-smb.

**Comment by mauriciopoppe** [comment]
We use https://github.com/kubernetes-csi/csi-release-tools as a git subtree in this repo to provide the scripts to builds images, to support this arm/v7 we need to:

- Verify that we can create an armv7 image locally, this is done by updating [`release-tools/prows.sh`](https://github.com/kubernetes-csi/external-provisioner/blob/master/release-tools/prow.sh#L81) and running `make push-{repo}`.
- Once we verify that it was added, we need to make the change permanent in https://github.com/kubernetes-csi/csi-release-tools/blob/4aedf357cac90c044cf3c2b8ff189520e3fd37b2/prow.sh#L81, a PR should be merged that adds that version.
- Sync the git subtree at `./release-tools`
- Release a new version, on postsubmit the staging image for arm/v7 should be created.
- Promote the images to the release repo.

This strategy follows what we did in the past for `linux/arm` https://github.com/kubernetes-csi/node-driver-registrar/pull/161.

**Comment by fidesachates** [comment]
@mauriciopoppe Thank you for the explanation. From what I've seen, it seems[ your step three is done](https://github.com/kubernetes-csi/external-provisioner/commit/2bd55be61ea30ff2bfc9cc05cd431676eb79cb97)? Is that right? 

I'm not familiar with where staging images are stored so I can't check it. Can you confirm for me where we are in the process and how long you expect this to take? Not trying to put pressure, but just want to set my own expectations so I can determine the best course for  me (i.e. wait or try another path)

**Comment by mauriciopoppe** [comment]
All these steps should be done in order, i.e. we can only sync the git subtree after making the changes in https://kubernetes-csi/csi-release-tools@4aedf35/prow.sh#L81. For the timeline I think we haven't released this project in 1.23 yet according to https://github.com/orgs/kubernetes-csi/projects/49, so there might be time to include this change, I'm not sure when it'll be released though.

**Comment by fidesachates** [comment]
@mauriciopoppe am I right that the git subtree has already been synced though? Here's the commit that makes me believe this as it contains the prow file change. https://github.com/kubernetes-csi/external-provisioner/commit/2bd55be61ea30ff2bfc9cc05cd431676eb79cb97

**Comment by mauriciopoppe** [comment]
it has been synced but we haven't made the change to support armv7 yet and therefore we need to do another git subtree sync after the feature is added in [kubernetes-csi/csi-release-tools@4aedf35/prow.sh#L81](https://kubernetes-csi/csi-release-tools@4aedf35/prow.sh#L81).
