### ISSUE TITLE
Tracker for v3.1.0 release

### ISSUE THREAD

**Issue by humblec** [kubernetes-csi/external-provisioner#692]
Eventhough we are pretty much ready for the next release based on 1.23 (https://github.com/kubernetes-csi/external-provisioner/pull/686) , it is yet to be done. This issue tracks the release.

**Comment by pohly** [comment]
I don't have permission to tag a release in this repo.

**Comment by humblec** [comment]
> I don't have permission to tag a release in this repo.

nw @pohly , and thanks @xing-yang for the release .. I am closing this issue as the release is now available
