### ISSUE TITLE
Failed to create PV if the secret name length is greater than 63 chars

### ISSUE THREAD

**Issue by Madhu-1** [kubernetes-csi/external-provisioner#708]
When the secret name length is greater than 63 chars the PV creation is failing with below error

```
I0217 10:30:34.838278       1 controller.go:860] Started provisioner controller rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-6d765b47d5-vpp4c_e448436b-7129-4228-8bfd-ca6a7ead8a5b!
I0224 02:48:28.628887       1 controller.go:1337] provision "default/rbd-pvc1" class "rook-ceph-block1": started
I0224 02:48:28.642229       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"rbd-pvc1", UID:"b29b319d-986f-4cd1-b537-cbf0e5ba62bb", APIVersion:"v1", ResourceVersion:"1339014", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/rbd-pvc1"
I0224 02:48:28.852218       1 controller.go:1442] provision "default/rbd-pvc1" class "rook-ceph-block1": volume "pvc-b29b319d-986f-4cd1-b537-cbf0e5ba62bb" provisioned
I0224 02:48:28.852668       1 controller.go:1455] provision "default/rbd-pvc1" class "rook-ceph-block1": succeeded
E0224 02:48:28.869627       1 volume_store.go:90] Failed to save volume pvc-b29b319d-986f-4cd1-b537-cbf0e5ba62bb: error saving volume pvc-b29b319d-986f-4cd1-b537-cbf0e5ba62bb: PersistentVolume "pvc-b29b319d-986f-4cd1-b537-cbf0e5ba62bb" is invalid: spec.csi.name: Invalid value: "rook-ceph-client-cephclient-rbd-provisioner-storageconsumer-129e6746-6ba2-4dfc-9a64-18bab83a695a": must be no more than 63 characters
E0224 02:48:28.872697       1 volume_store.go:144] error saving volume pvc-b29b319d-986f-4cd1-b537-cbf0e5ba62bb: PersistentVolume "pvc-b29b319d-986f-4cd1-b537-cbf0e5ba62bb" is invalid: spec.csi.name: Invalid value: "rook-ceph-client-cephclient-rbd-provisioner-storageconsumer-129e6746-6ba2-4dfc-9a64-18bab83a695a": must be no more than 63 characters
```

Steps to reproduce
* Create secret with name length greater than 63 chars
* Create storageclass (specify the secret name for provisioner and node secret)
* Create PVC

If the secret creation with a name greater than 63 chars are allowed and specifying the same length name is allowed in storageclass parameters why not allow the creation of PV objects?

**Comment by Madhu-1** [comment]
cc @jsafrane @msau42 @xing-yang

**Comment by Madhu-1** [comment]
As the issue is not in the external-provisioner, I created an issue here as it's trying to create the PV. it's a generic problem with both dynamic PVC and static PV. if we want I can open an issue in the kubernetes repo also.

**Comment by humblec** [comment]
Consider this field belong to metadata.name field where 63 chars limit validation has been imposed, I doubt this qualify as a bug,

**Comment by pohly** [comment]
PV.spec.csi is the [CSIPersistentVolumeSource](https://pkg.go.dev/k8s.io/api@v0.23.4/core/v1#CSIPersistentVolumeSource) in the PersistentVolumeSource, right? But it doesn't have a `name` field.

Is that perhaps referring to the `name` field in one of the secret references? Then validation in Kubernetes has a bug because it doesn't properly construct the field path.

Does the name validation there use stricter rules than the name validation for secret objects? @Madhu-1 said "Create secret with name length greater than 63 chars", so I am assuming that this worked.

**Comment by humblec** [comment]
> PV.spec.csi is the [CSIPersistentVolumeSource](https://pkg.go.dev/k8s.io/api@v0.23.4/core/v1#CSIPersistentVolumeSource) in the PersistentVolumeSource, right? But it doesn't have a `name` field.
> 
> Is that perhaps referring to the `name` field in one of the secret references? Then validation in Kubernetes has a bug because it doesn't properly construct the field path.
> 

afaict, the `csi.spec.name` field validation caught `secretReference->name` in its path here and validation is currently imposed with 63 char limit we have on `CSI->Name` field by the CSI spec. 
 
> Does the name validation there use stricter rules than the name validation for secret objects? @Madhu-1 said "Create secret with name length greater than 63 chars", so I am assuming that this worked.

It will work, as mentioned in above comment the secret object name has to be DNS subdomain name which is "253" char,

**Comment by Madhu-1** [comment]
> PV.spec.csi is the [CSIPersistentVolumeSource](https://pkg.go.dev/k8s.io/api@v0.23.4/core/v1#CSIPersistentVolumeSource) in the PersistentVolumeSource, right? But it doesn't have a `name` field.
> 
> Is that perhaps referring to the `name` field in one of the secret references? Then validation in Kubernetes has a bug because it doesn't properly construct the field path.
> 

yes its the secret name field 

> Does the name validation there use stricter rules than the name validation for secret objects? @Madhu-1 said "Create secret with name length greater than 63 chars", so I am assuming that this worked.

Yes, the creation of secrets is allowed till the limit of 253 chars but reference it is not allowed in the PV object.

@pohly we need to decide we need to increase the char limit in the validation or not. at least if not possible fail fast before provisioning the PV or creating the storage resources. it does not make sense to create all the storage resources and fail to create the PV. This can also cause the storage resource leak like https://github.com/kubernetes-csi/external-provisioner/issues/486

**Comment by jsafrane** [comment]
It seems like a bug in the validation, `Secret.Name` is validated by [NameIsDNSSubdomain](https://github.com/kubernetes/kubernetes/blob/016b96ca3896d27b37c5b2d6e223fb3320a0fdec/pkg/apis/core/validation/validation.go#L278) (253 characters), while [ValidateDNS1123Label](https://github.com/kubernetes/kubernetes/blob/016b96ca3896d27b37c5b2d6e223fb3320a0fdec/pkg/apis/core/validation/validation.go#L1567) is used to validate the secret refs (63 characters).

In addition, the field path is constructed wrong after all `ValidateDNS1123Label` calls: https://github.com/kubernetes/kubernetes/blob/016b96ca3896d27b37c5b2d6e223fb3320a0fdec/pkg/apis/core/validation/validation.go#L1564-L1568

It's interesting that `field.Required` errors are reported correctly (`controllerPublishSecretRef.name`), while `ValidateDNS1123Label` errors use only `name`.

**Comment by jsafrane** [comment]
In other words, feel free to fix the secret ref validation to use `ValidateSecretName()` instead of `ValidateDNS1123Label`.
And please fix the field reporting, this is very confusing.

**Comment by humblec** [comment]
Thanks @jsafrane , indeed this is confusing and goes wrong in the validation path.
