### ISSUE TITLE
The  status of the pv is always Terminating.

### ISSUE THREAD

**Issue by zhucan** [kubernetes-csi/external-provisioner#718]
The log in the external-provisoner:
![image](https://user-images.githubusercontent.com/13997135/159719591-06fb3d16-92b2-4442-b746-925806cf85a4.png)

But the pv'status is Terminating:
![image](https://user-images.githubusercontent.com/13997135/159719763-0dcae968-b6c4-4848-8774-9d5f68d93709.png)

NodeExpandVoume not exec, Only ControllerExpandVolume exec, the size of pvc not equal to the pv.(Because of the volume was not used by pod), so the NodeExpandVolume will not trigger. In this case, we delete the pvc.

**Comment by humblec** [comment]
hmmm.. this is interesting.. 

Looks like this is the workflow you are performing.. can you please confirm? 
```
PVC is bound to "PV" but not yet attached to POD.. 
Expanded the PVC
Controller Expand was successful, however nodeExpansion pending..
Delete PVC.
PV status at terminating... 

```

it seems to me that, if PVC is deleted and if its successfully deleted the PV too, te get PV should be not in `terminating` state.. and looks like a bug to me if this is happening.. have to reproduce and check further.
 
Cc @jsafrane

**Comment by zhucan** [comment]
@humblec Yes, the same procedure with you.
