### ISSUE TITLE
Creating PVC from a snapshot with restoreSize larger than PVC request size.

### ISSUE THREAD

**Issue by kaovilai** [kubernetes-csi/external-provisioner#727]
Reverse issue from #485

**User story:**
Created PVC-A with 100MiB request (external provisioner gives back capacity higher than requested, for whatever reason)
Create VolumeSnapshot-A - snapshot created with **restore size = PV capacity > PVC storage request**.
Create new 100MiB request PVC-B using snapshot VolumeSnapshot-A as data source which has restoreSize > PVC storage request

**Expectation:**
New PVC can be created from a volumesnapshot created from another PVC of the same request size regardless of the source PVC resulting capacity and therefore volumesnapshot restoreSize.

**Suggested resolution:**
As long as capacity is allowed to be higher than requested size, then snapshot restoreSize larger than request should be a valid source to create PVC. Either by default, or with a flag `resizeRequests: true`

PVC resource request only means minimum size, and should be treated as such. PVC size should be allowed to grow when dataSource used is larger.

Current code that will need to change to satisfy this request:
https://github.com/kubernetes-csi/external-provisioner/blob/0456e7315a07228c16360a57a611aa0a1279fcdc/pkg/controller/controller.go#L1100

**Comment by kaovilai** [comment]
Not sure if this behavior exists for internal-provisioners as well.. if so it would be great to have those cases handled too.

**Comment by xing-yang** [comment]
This seems to be a duplicate of https://github.com/kubernetes-csi/external-provisioner/issues/485.
