### ISSUE TITLE
CSIStorageCapacity: Topology segment not updated

### ISSUE THREAD

**Issue by samuelluohaoen1** [kubernetes-csi/external-provisioner#847]
**What happened**:
After new node plugins join the cluster and report new AccessibleTopologies.Segments, the current segment information is not getting updated. New *CSIStorageCapacity* objects are not being created.

**What you expected to happen**:
New node plugins reporting new values for existing topology segments should in a sense "expand" the value sets of existing topology segments. Which in turn should result in *CSIStorageCapacity* objects being created for new accessible segments.

**How to reproduce it**:
1. Suppose the *CSIDriver* has name `com.foo.bar`. Check that `STORAGECAPACITY` is true.
2. Deploy controller plugin but not node plugin. Wait for *external-provisioner* to print "Initial number of topology segments 0, storage classes 0, potential CSIStorageCapacity objects 0" (To see this log run *external-provisioner* with log level 5).
3. Now *CSINode* should have `DRIVERS: 0`.
4. Deploy the node plugin. Wait for the `NodeGetInfo` RPC to be called. The RPC should return something like 
```json
{
    "NodeId": "some-node",
    "AccessibleTopologies": {
        "Segments": [
            "kubernetes.io/hostname": "some-node"
        ]
    }
}
```
5. Now *CSINode* should have `DRIVERS: 1` which is named `com.foo.bar` with `Node ID: some-node` and `Topology Keys: [kubernetes.io/hostname]`.
6. Deploy a *StorageClass* with `volumeBindingMode: WaitForFirstConsumer` and `provisioner: com.foo.bar`.
7. No new *CSIStorageCapacity* object is created.

**Anything else we need to know?**:
I am using the "kubernetes.io/hostname" label as the only key because we want topology to be constraint by each node. Each PV is to be provisioned locally on some node. I also assumed that "kubernetes.io/hostname" is unique across the nodes and should by default exist on every node (I hope this is a reasonable assumption).

**Environment**:
- Driver version: v3.0.0
- Kubernetes version (use `kubectl version`): 1.25+
- OS (e.g. from /etc/os-release): Our in-house OS which is very similar to CentOS 
- Kernel (e.g. `uname -a`):  Linux 4.18.0
- Install tools: kubeadm
- Others: 

@pohly

**Comment by pohly** [comment]
> No new CSIStorageCapacity object is created.

How do you check for this? With `kubectl get csistoragecapacities` or `kubectl get --all-namespaces csistoragecapacities`?

CSIStorageCapacity objects are namespaced, so the second command has to be used.

I tried to reproduce the issue with csi-driver-host-path v1.10.0, but there I get new CSIStorageCapacity objects after creating a storage class.

**Comment by pohly** [comment]
My commands:
```
/deploy/kubernetes-distributed/deploy.sh
kubectl delete storageclass.storage.k8s.io/csi-hostpath-slow
kubectl delete storageclass.storage.k8s.io/csi-hostpath-fast
kubectl get --all-namespaces csistoragecapacity
kubectl create -f deploy/kubernetes-distributed/hostpath/csi-hostpath-storageclass-fast.yaml
kubectl get --all-namespaces csistoragecapacity
```

**Comment by pohly** [comment]
csi-provisioner:v3.3.0

**Comment by samuelluohaoen1** [comment]
> > No new CSIStorageCapacity object is created.
> 
> How do you check for this? With `kubectl get csistoragecapacities` or `kubectl get --all-namespaces csistoragecapacities`?
> 
> CSIStorageCapacity objects are namespaced, so the second command has to be used.
> 
> I tried to reproduce the issue with csi-driver-host-path v1.10.0, but there I get new CSIStorageCapacity objects after creating a storage class.

Yes it is indeed namespaced. My kubectl has the default namespace set to the namespace where the CSI plugins are deployed.

**Comment by samuelluohaoen1** [comment]
> My commands:
> 
> ```
> /deploy/kubernetes-distributed/deploy.sh
> kubectl delete storageclass.storage.k8s.io/csi-hostpath-slow
> kubectl delete storageclass.storage.k8s.io/csi-hostpath-fast
> kubectl get --all-namespaces csistoragecapacity
> kubectl create -f deploy/kubernetes-distributed/hostpath/csi-hostpath-storageclass-fast.yaml
> kubectl get --all-namespaces csistoragecapacity
> ```

From the sequence of your commands I do not see how the controller plugin is deployment before the node plugins. I think the order of the deployment may be crucial to reproducing this issue. Could you make sure that step 2 happens before node plugins are deployed? Thank you for your trouble.

**Comment by pohly** [comment]
@samuelluohaoen1: it looks like you are using a central controller for your CSI driver. Is that correct?

Can you perhaps share the external-provisioner log at level >= 5? The is [code](https://github.com/kubernetes-csi/external-provisioner/blob/6c7db2ccbc0a40c41d0d68351d3b654617766588/pkg/capacity/topology/nodes.go#L58-L61) which should react to changes in the node and CSIDriver objects when the node plugin gets registered after the controller has started. 

We don't have a CSI driver deployment readily available to test this scenario. I tried reproducing it through unit tests (see https://github.com/kubernetes-csi/external-provisioner/pull/942) but the code worked as expected.

**Comment by yuxiang-he** [comment]
@pohly We observed something similar but the `CSIStorageCapacity` objects are created after about an hour.

I believe there is currently an issue where the capacity controller is tracking duplicated workqueue entries. See issue https://github.com/kubernetes-csi/external-provisioner/issues/1161
