### ISSUE TITLE
Why is VolumeAttributes not passed in csi.DeleteVolumeRequest?

### ISSUE THREAD

**Issue by avagin** [kubernetes-csi/external-provisioner#87]
VolumeAttributes can contains properties which may be useful for deleting volumes.

**Comment by sarjeet2013** [comment]
+1. 

`DeleteVolume` may require additional info to fulfill the delete request which can be provided by VolumeAttributes passed to `DeleteVolume` along with `volumeId` and `Secrets`.

**Comment by xing-yang** [comment]
@sarjeet2013 Can you use Secrets to store the server info you need?  
See https://github.com/container-storage-interface/spec/blob/master/spec.md#secrets-requirements  and 
https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by sarjeet2013** [comment]
@xing-yang I discussed it internally but it seems an overhead in adding server info as secret (which doesn't make sense at all) which can be passed easily as parameters from `StorageClass`. 

Also, it adds another resource (server info Secret) to be created before `StorageClass` is created.

**Comment by msau42** [comment]
This is a question for the CSI spec.

Related discussions:
https://github.com/container-storage-interface/spec/issues/29
https://github.com/container-storage-interface/spec/issues/216
https://github.com/container-storage-interface/spec/issues/167
