### ISSUE TITLE
DeleteVolume is called twice when deleting a volume

### ISSUE THREAD

**Issue by clintonk** [kubernetes-csi/external-provisioner#89]
Around half the time, I see DeleteVolume called twice when deleting a PVC.  The delete is idempotent, so the second call is harmless and does not return an error, but it'd be nice to avoid it or at least understand why it happens.

Here's a log snippet of my CSI controller when deleting a single PVC.  Note the duplicate DeleteVolume calls about 1 second apart:

    DEBU[0613] GRPC call: /csi.v0.Identity/GetPluginCapabilities 
    DEBU[0613] GRPC request:                                
    DEBU[0613] >>>> GetPluginCapabilities                    Method=GetPluginCapabilities Type=CSI_Identity
    DEBU[0613] <<<< GetPluginCapabilities                    Method=GetPluginCapabilities Type=CSI_Identity
    DEBU[0613] GRPC response: capabilities:<service:<type:CONTROLLER_SERVICE > >  
    DEBU[0613] GRPC call: /csi.v0.Controller/ControllerGetCapabilities 
    DEBU[0613] GRPC request:                                
    DEBU[0613] >>>> ControllerGetCapabilities                Method=ControllerGetCapabilities Type=CSI_Controller
    DEBU[0613] <<<< ControllerGetCapabilities                Method=ControllerGetCapabilities Type=CSI_Controller
    DEBU[0613] GRPC response: capabilities:<rpc:<type:CREATE_DELETE_VOLUME > > capabilities:<rpc:<type:PUBLISH_UNPUBLISH_VOLUME > > capabilities:<rpc:<type:LIST_VOLUMES > >  
    DEBU[0613] GRPC call: /csi.v0.Identity/GetPluginInfo    
    DEBU[0613] GRPC request:                                
    DEBU[0613] >>>> GetPluginInfo                            Method=GetPluginInfo Type=CSI_Identity
    DEBU[0613] <<<< GetPluginInfo                            Method=GetPluginInfo Type=CSI_Identity
    DEBU[0613] GRPC response: name:"io.netapp.trident.csi" vendor_version:"18.07.0"  
    DEBU[0613] GRPC call: /csi.v0.Controller/DeleteVolume
    DEBU[0613] GRPC request: volume_id:"{\"name\":\"pvc-f3aafe455ad011e8\",\"protocol\":\"file\"}"  
    DEBU[0613] >>>> DeleteVolume                             Method=DeleteVolume Type=CSI_Controller
    DEBU[0614] <<<< DeleteVolume                             Method=DeleteVolume Type=CSI_Controller
    DEBU[0614] GRPC response:                               
    DEBU[0614] GRPC call: /csi.v0.Identity/GetPluginCapabilities 
    DEBU[0614] GRPC request:                                
    DEBU[0614] >>>> GetPluginCapabilities                    Method=GetPluginCapabilities Type=CSI_Identity
    DEBU[0614] <<<< GetPluginCapabilities                    Method=GetPluginCapabilities Type=CSI_Identity
    DEBU[0614] GRPC response: capabilities:<service:<type:CONTROLLER_SERVICE > >  
    DEBU[0614] GRPC call: /csi.v0.Controller/ControllerGetCapabilities 
    DEBU[0614] GRPC request:                                
    DEBU[0614] >>>> ControllerGetCapabilities                Method=ControllerGetCapabilities Type=CSI_Controller
    DEBU[0614] <<<< ControllerGetCapabilities                Method=ControllerGetCapabilities Type=CSI_Controller
    DEBU[0614] GRPC response: capabilities:<rpc:<type:CREATE_DELETE_VOLUME > > capabilities:<rpc:<type:PUBLISH_UNPUBLISH_VOLUME > > capabilities:<rpc:<type:LIST_VOLUMES > >  
    DEBU[0614] GRPC call: /csi.v0.Identity/GetPluginInfo    
    DEBU[0614] GRPC request:                                
    DEBU[0614] >>>> GetPluginInfo                            Method=GetPluginInfo Type=CSI_Identity
    DEBU[0614] <<<< GetPluginInfo                            Method=GetPluginInfo Type=CSI_Identity
    DEBU[0614] GRPC response: name:"io.netapp.trident.csi" vendor_version:"18.07.0"  
    DEBU[0614] GRPC call: /csi.v0.Controller/DeleteVolume
    DEBU[0614] GRPC request: volume_id:"{\"name\":\"pvc-f3aafe455ad011e8\",\"protocol\":\"file\"}"  
    DEBU[0614] >>>> DeleteVolume                             Method=DeleteVolume Type=CSI_Controller
    DEBU[0614] Could not delete volume.                      error="volume pvc-f3aafe455ad011e8 not found" volumeName=pvc-f3aafe455ad011e8
    DEBU[0614] <<<< DeleteVolume                             Method=DeleteVolume Type=CSI_Controller
    DEBU[0614] GRPC response:

**Comment by venkatsc** [comment]
I am also using `csi-provisioner:v0.2.0` and with recent versions of Kubernetes received duplicate CreateVolume request.

**Comment by msau42** [comment]
There have been various fixes to timeouts and retries in the external-provisioner in the 1.1 release: https://github.com/kubernetes-csi/external-provisioner/blob/master/CHANGELOG-1.1.md.  Please try 1.1+ and see if that fixes your issue.

/close
