### ISSUE TITLE
NodeStageVolume is called before each call to NodePublishVolume

### ISSUE THREAD

**Issue by clintonk** [kubernetes-csi/external-provisioner#90]
With a CSI plugin that works with iSCSI targets, I have to support the STAGE_UNSTAGE_VOLUME node capability.  If I mount an iSCSI volume to three pods on the same host, then later delete all three pods, the spec says I _should_ see this sequence:

* ControllerPublishVolume
  * NodeStageVolume
    * NodePublishVolume
    * NodePublishVolume
    * NodePublishVolume
    * NodeUnpublishVolume
    * NodeUnpublishVolume
    * NodeUnpublishVolume
  * NodeUnstageVolume
* ControllerUnpublishVolume

Instead, I see:

* ControllerPublishVolume
  * NodeStageVolume
    * NodePublishVolume
    * NodeStageVolume
    * NodePublishVolume
    * NodeStageVolume
    * NodePublishVolume
    * NodeUnpublishVolume
    * NodeUnpublishVolume
    * NodeUnpublishVolume
  * NodeUnstageVolume
* ControllerUnpublishVolume

The extra calls to NodeStageVolume are idempotent/harmless, but it'd be nice to avoid the unnecessary work.

**Comment by princerachit** [comment]
Please enable kubelet logging level 4 with `--v=4` and share the logs of kubelet corresponding to node stage volue calls.

**Comment by clintonk** [comment]
Requested kubelet log attached.  It shows the result of creating 3 pods, all of which use the same iSCSI PV.  NodeStageVolume is called 3 times, once for each pod.

[kubelet-csi-multi-stage.txt](https://github.com/kubernetes-csi/external-provisioner/files/2156752/kubelet-csi-multi-stage.txt)

**Comment by msau42** [comment]
@clintonk is this still an issue? What version of Kubernetes are you using?

At least in latest Kubernetes, it should check that the volume is already mounted and [return early](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_attacher.go#L284)

**Comment by clintonk** [comment]
@msau42 Yes, I still observe this issue with Kubernetes 1.13 and the associated 1.0.x sidecars.  I will retest with 1.14+.

**Comment by msau42** [comment]
Need help on repro + investigation
/help

**Comment by msau42** [comment]
Actually this bug should be reported to k/k, not external-provisioner

**Comment by msau42** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/82838 for tracking. closing this one
