### ISSUE TITLE
Facing vulnerability issues with net

### ISSUE THREAD

**Issue by kalpanathanneeru21** [kubernetes-csi/external-provisioner#904]
Facing vulnerability issues with net since it is older version
are there upcoming releases are going have fixes for these vulnerabilities

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Driver version: EFS_VERSION=v1.5.4
- Provisioner version: v3.4.0-eks-1-25-8
- Kubernetes version (use `kubectl version`): 1.22
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by coltonfreeman26** [comment]
Good day all,
With sig-storage/csi-provisioner:3.6.0 our scan tools have found two medium findings in regards to /x/net-v0.14.0 both of which are fixed with 0.17.0
Are there any plans to update this?
