### ISSUE TITLE
csi.Provision() drops PVC information which existing external-provisioners use

### ISSUE THREAD

**Issue by mkimuram** [kubernetes-csi/external-provisioner#93]
In some existing external-provisioners, PVC information is used on Provision().
For example, 
  - Gluster:
    https://github.com/kubernetes-incubator/external-storage/blob/master/gluster/file/cmd/glusterfile-provisioner/glusterfile-provisioner.go#L199
    (It uses options.PVC.Annotations.)
  - NFS:
    https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/cmd/nfs-client-provisioner/provisioner.go#L61 
    (It uses options.PVC.Namespace and options.PVC.Name.)

In current CSI external-provisioner implementation, on the other hand, PVC information, or options.PVC, is dropped, because it only set part of information(*1) and pass it to csiClient.CreateVolume() (*2).

  (*1) Setting some of parameters to req:
  https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L299
  (*2) Passing req to csiClient.CreateVolume():
  https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L345

As a result, external-provisioners which use PVC information to provision their volume can't be reimplemented to CSI external-provisioner.

Therefore, we should pass PVC information to csiClient.CreateVolume(), either by
1. Adding PVC information to options.Parameters,
2. Adding argument for PVC to CreateVolume().

I guess 1. is better because 2. requires change in spec for CSI. https://github.com/container-storage-interface/spec/blob/master/spec.md#createvolume

**Comment by princerachit** [comment]
+1

**Comment by mkimuram** [comment]
Closing this issue for general PVC information with the conclusion in the below thread.
We will keep discussion on PVC annotation in the below thread.

https://github.com/kubernetes-csi/external-provisioner/issues/86#issuecomment-397012310

>Today's discussion concluded that we are not going to immediately touch the spec for CreateVolumeRequest to pass CO specific metadata(PVC name,PVC id etc). A proposed workaround is to write your own external provisioner which knows what params to pass for your specific driver.
