### ISSUE TITLE
External Provisioner Change

### ISSUE THREAD

**Issue by sunnylovestiramisu** [kubernetes-csi/external-provisioner#952]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-e776b8fa-7fff-5a33-682c-79ecb0343e5e"><div dir="ltr" style="margin-left:0pt;" align="left">

Tasks
--
0. Feature gate for provisioner specific VolumeAttributesClass change
1. Add support for provision PVC with a VolumeAttributesClass

</div></b>

**Comment by sunnylovestiramisu** [comment]
Is there a PR being submitted for review yet?

**Comment by ConnorJC3** [comment]
@sunnylovestiramisu I was waiting for https://github.com/kubernetes/kubernetes/pull/118863 to be merged first, but if you want I could create a PR based on that PR's version of the APIs.

**Comment by sunnylovestiramisu** [comment]
@ConnorJC3 feel free to create a PR ahead and get an early review ahead of the schedule :)

**Comment by sunnylovestiramisu** [comment]
FYI, the api change got separated and you can try to pull this change down locally in external-provisioner and make a change: https://github.com/kubernetes/kubernetes/pull/121104/files
